#pragma kernel CSMain
#include "Assets/_Project/Utils/Shaders/Math.cginc"

RWTexture2D<float4> c_result;
int c_texture_size;
#define NUM_OUT_SCATTERING_STEPS 10
float c_atmosphere_radius;
float c_density_falloff;

float densityAtPoint(float2 densitySamplePoint) {
	float planetRadius = 1;
	float2 planetCentre = 0;

	float heightAboveSurface = length(densitySamplePoint - planetCentre) - planetRadius;
	float height01 = heightAboveSurface / (c_atmosphere_radius - planetRadius);
	float localDensity = exp(-height01 * c_density_falloff) * (1 - height01);
	return localDensity;
}

float opticalDepth(float2 rayOrigin, float2 rayDir, float rayLength) {
	float2 densitySamplePoint = rayOrigin;
	float stepSize = rayLength / (NUM_OUT_SCATTERING_STEPS - 1);
	float opticalDepth = 0;

	for (int i = 0; i < NUM_OUT_SCATTERING_STEPS; i ++) {
		float localDensity = densityAtPoint(densitySamplePoint);
		opticalDepth += localDensity * stepSize;
		densitySamplePoint += rayDir * stepSize;
	}
	return opticalDepth;
}


float calculateOutScattering(float2 inPoint, float2 outPoint) {
	float planetRadius = 1;
	float skinWidth = planetRadius / 1000.0;
	

	float lightTravelDst = length(outPoint - inPoint);
	float2 outScatterPoint = inPoint;
	float2 rayDir = (outPoint - inPoint) / lightTravelDst;
	float stepSize = (lightTravelDst - skinWidth) / (NUM_OUT_SCATTERING_STEPS);
	
	float outScatterAmount = 0;

	for (int i = 0; i < NUM_OUT_SCATTERING_STEPS; i ++) {
		outScatterPoint += rayDir * stepSize;

		// height at planet surface = 0, at furthest extent of atmosphere = 1
		float height = length(outScatterPoint - 0) - planetRadius;//

	
		
		float height01 = saturate(height / (c_atmosphere_radius - planetRadius));
		outScatterAmount += exp(-height01 * c_density_falloff) * stepSize;
		
	}

	return outScatterAmount;
}

[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
	const float planetRadius = 1;

	float2 uv = id / (float)c_texture_size;
	float height01 = uv.y;
	float angle = uv.x * 3.14159265359;
	float2 dir = float2(sin(angle), cos(angle));
	float y = -2 * uv.x + 1;
	float x = sin(acos(y));
	dir = float2(x,y);
	
	float2 inPoint = float2(0, lerp(planetRadius, c_atmosphere_radius, height01));
	float dstThroughAtmosphere = ray_sphere(0, c_atmosphere_radius, float3(inPoint,0), float3(dir,0)).y;
	float2 outPoint = inPoint + dir * ray_sphere(0, c_atmosphere_radius, float3(inPoint,0), float3(dir,0)).y;
	float outScattering = opticalDepth(inPoint + dir * 0.0001, dir, dstThroughAtmosphere-0.0002);

	c_result[id.xy] = outScattering;
}