Openworld Factory (Name WIP): _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer Class Reference
_Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer Class Reference
Public Member Functions
void SetPlanetManager (PlanetManager planetManager)
Private Member Functions
void Awake ()
void Update ()
void OnDestroy ()
Private Attributes
PlanetManager _planetManager
FrustumCullingSystem _frustumCullingSystem
Camera viewer
Detailed Description
Definition at line 6 of file PlanetRenderer.cs.
Member Function Documentation
Awake()
void _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Awake () inline private
Definition at line 19 of file PlanetRenderer.cs.
        {
            _frustumCullingSystem = new FrustumCullingSystem();
        }
References _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._frustumCullingSystem.
OnDestroy()
void _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.OnDestroy () inline private
Definition at line 33 of file PlanetRenderer.cs.
        {
            _planetManager.Dispose();
        }
References _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._planetManager, and _Project.World.Planet.Scripts.v2.PlanetManager.Dispose().
SetPlanetManager()
void _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.SetPlanetManager (PlanetManager planetManager) inline
Definition at line 14 of file PlanetRenderer.cs.
        {
            _planetManager = planetManager;
        }
References _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._planetManager.
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable().
Update()
void _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update () inline private
Definition at line 25 of file PlanetRenderer.cs.
        {
            _frustumCullingSystem.Update(
                _planetManager.Octree,
                viewer
            );
        }
References _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._frustumCullingSystem, _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._planetManager, _Project.World.Planet.Scripts.v2.PlanetManager.Octree, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update(), and _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.viewer.
Member Data Documentation
_frustumCullingSystem
FrustumCullingSystem _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._frustumCullingSystem private
Definition at line 10 of file PlanetRenderer.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Awake(), and _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update().
_planetManager
PlanetManager _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer._planetManager private
Definition at line 8 of file PlanetRenderer.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.OnDestroy(), _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.SetPlanetManager(), and _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update().
viewer
Camera _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.viewer private
Definition at line 12 of file PlanetRenderer.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update().
The documentation for this class was generated from the following file:
World/Planet/Scripts/v2/Rendering/PlanetRenderer.cs