Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Deprecated.PlanetCube Class Reference
_Project.World.Planet.Scripts.Deprecated.PlanetCube Class Reference
Public Attributes
int resolution = 10
Private Member Functions
void Start ()
void OnValidate ()
void Update ()
void Initialize ()
void GenerateMesh ()
Private Attributes
bool _needsGeneration
MeshFilter[] meshFilters
TerrainFace[] _terrainFaces
Detailed Description
Definition at line 7 of file PlanetCube.cs.
Member Function Documentation
GenerateMesh()
void _Project.World.Planet.Scripts.Deprecated.PlanetCube.GenerateMesh () inline private
Definition at line 106 of file PlanetCube.cs.
        {
            if (_terrainFaces == null) return;
            foreach (TerrainFace face in _terrainFaces)
            {
                face.ConstructMesh();
            }
        }
References _Project.World.Planet.Scripts.Deprecated.PlanetCube._terrainFaces, and _Project.World.Planet.Scripts.Deprecated.TerrainFace.ConstructMesh().
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.Start(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Update().
Initialize()
void _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize () inline private
Definition at line 49 of file PlanetCube.cs.
        {
            // Ensure we always have 6 mesh slots (cube faces)
            if (meshFilters == null || meshFilters.Length != 6)
            {
                meshFilters = new MeshFilter[6];
            }
            _terrainFaces = new TerrainFace[6];
            // Directions for each cube face
            Vector3[] directions =
            {
                Vector3.up, Vector3.down,
                Vector3.left, Vector3.right,
                Vector3.forward, Vector3.back
            };
            for (int i = 0; i < 6; i++)
            {
                // Create mesh objects if they don't exist yet
                if (meshFilters[i] == null)
                {
                    // Try to find existing children first
                    Transform child = transform.Find("mesh_" + i);
                    if (child != null)
                    {
                        meshFilters[i] = child.GetComponent<MeshFilter>();
                    }
                    else
                    {
                        GameObject meshObj = new GameObject("mesh_" + i)
{
                            transform =
{
                                // Parent meshes to the planet object
                                parent = transform
                            }
                        };
                        // Add renderer + material
                        meshObj.AddComponent<MeshRenderer>()
                            .sharedMaterial = new Material(Shader.Find("Standard"));
                        // Add mesh filter with empty mesh
                        meshFilters[i] = meshObj.AddComponent<MeshFilter>();
                        meshFilters[i].sharedMesh = new Mesh();
                    }
                }
                // Create a terrain face pointing in one cube direction
                _terrainFaces[i] = new TerrainFace(meshFilters[i].sharedMesh, resolution, directions[i]);
            }
        }
References _Project.World.Planet.Scripts.Deprecated.PlanetCube._terrainFaces, _Project.World.Planet.Scripts.Deprecated.PlanetCube.meshFilters, and _Project.World.Planet.Scripts.Deprecated.PlanetCube.resolution.
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.Start(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Update().
OnValidate()
void _Project.World.Planet.Scripts.Deprecated.PlanetCube.OnValidate () inline private
Definition at line 27 of file PlanetCube.cs.
        {
            // Just set the flag, do NO structural work here
            if (gameObject.activeInHierarchy)
            {
                _needsGeneration = true;
            }
        }
References _Project.World.Planet.Scripts.Deprecated.PlanetCube._needsGeneration.
Start()
void _Project.World.Planet.Scripts.Deprecated.PlanetCube.Start () inline private
Definition at line 20 of file PlanetCube.cs.
        {
            Initialize();
            GenerateMesh();
        }
References _Project.World.Planet.Scripts.Deprecated.PlanetCube.GenerateMesh(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize().
Update()
void _Project.World.Planet.Scripts.Deprecated.PlanetCube.Update () inline private
Definition at line 36 of file PlanetCube.cs.
        {
            // update is safe for structural change to meshes etc
            if (_needsGeneration)
            {
                Initialize();
                GenerateMesh();
                // Reset the flag so it only runs once per change
                _needsGeneration = false;
            }
        }
References _Project.World.Planet.Scripts.Deprecated.PlanetCube._needsGeneration, _Project.World.Planet.Scripts.Deprecated.PlanetCube.GenerateMesh(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize().
Member Data Documentation
_needsGeneration
bool _Project.World.Planet.Scripts.Deprecated.PlanetCube._needsGeneration private
Definition at line 10 of file PlanetCube.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.OnValidate(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Update().
_terrainFaces
TerrainFace [] _Project.World.Planet.Scripts.Deprecated.PlanetCube._terrainFaces private
Definition at line 18 of file PlanetCube.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.GenerateMesh(), and _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize().
meshFilters
MeshFilter [] _Project.World.Planet.Scripts.Deprecated.PlanetCube.meshFilters private
Definition at line 15 of file PlanetCube.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize().
resolution
int _Project.World.Planet.Scripts.Deprecated.PlanetCube.resolution = 10
Definition at line 13 of file PlanetCube.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.PlanetCube.Initialize().
The documentation for this class was generated from the following file:
Assets/_Project/World/Planet/Scripts/Deprecated/PlanetCube.cs