Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap Class Reference
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap Class Reference
the chunk system bootstrap is the unity component that manages the chunks. you have to apply the renderer that renders the chunks and a settings object for further customization. a viewer is also required for streaming the chunks around that object. the main camera is recommended.
Private Member Functions
void OnEnable ()
void OnDisable ()
Private Attributes
GridChunkSystemSettings settings
new GridChunkSystemRenderer renderer
Transform viewer
GridChunkManager _chunkManager
Detailed Description
the chunk system bootstrap is the unity component that manages the chunks. you have to apply the renderer that renders the chunks and a settings object for further customization. a viewer is also required for streaming the chunks around that object. the main camera is recommended.
Definition at line 9 of file GridChunkSystemBootstrap.cs.
Member Function Documentation
OnDisable()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnDisable () inline private
Definition at line 41 of file GridChunkSystemBootstrap.cs.
        {
            if (renderer != null) // if there is a renderer assigned we need to dispose it and its components to prevent memory leaks and other issues
            {
                renderer.SetChunkManager(null); // "remove" the chunk manager
                renderer.SetViewer(null); // and viewer
            }
            _chunkManager = null; // remove the chunk manager object reference
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap._chunkManager, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.renderer, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetChunkManager(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetViewer().
OnEnable()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable () inline private
Definition at line 17 of file GridChunkSystemBootstrap.cs.
        {
            if (renderer == null) // only add a renderer if the current one is not set
            {
                renderer = GetComponent<GridChunkSystemRenderer>();
            }
            if (settings == null) // the user has to specify the settings themselves so if the settings arent specified when the object is instantiated we throw an error
            {
                Debug.LogError("GridChunkSystemSettings is missing.", this);
                return;
            }
            if (renderer == null) // same goes for the renderer
            {
                Debug.LogError("GridChunkSystemRenderer is missing.", this);
                return;
            }
            _chunkManager = settings.CreateManager(); // create the chunk manager based on the settings. this is where the logic of the chunk system is being created.
            renderer.SetChunkManager(_chunkManager); // apply the chunk manager to the renderer
            renderer.SetViewer(viewer);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap._chunkManager, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemSettings.CreateManager(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.renderer, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetChunkManager(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.settings, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetViewer(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.viewer.
Member Data Documentation
_chunkManager
GridChunkManager _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap._chunkManager private
Definition at line 15 of file GridChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
renderer
new GridChunkSystemRenderer _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.renderer private
Definition at line 12 of file GridChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
settings
GridChunkSystemSettings _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.settings private
Definition at line 11 of file GridChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
viewer
Transform _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.viewer private
Definition at line 13 of file GridChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/GridChunkSystem/Unity/GridChunkSystemBootstrap.cs