Openworld Factory (Name WIP): _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap Class Reference
_Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap Class Reference
Public Member Functions
void RebuildOctree ()
Private Member Functions
void OnEnable ()
void OnDisable ()
void HandleSettingsChanged (PlanetConfig config)
Private Attributes
PlanetSettings settings
new PlanetRenderer renderer
PlanetManager _planetManager
Detailed Description
Definition at line 8 of file PlanetBootstrap.cs.
Member Function Documentation
HandleSettingsChanged()
void _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.HandleSettingsChanged (PlanetConfig config) inline private
Definition at line 32 of file PlanetBootstrap.cs.
        {
            _planetManager.UpdateConfig(config);
        }
References _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap._planetManager, and _Project.World.Planet.Scripts.v2.PlanetManager.UpdateConfig().
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnDisable(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable().
OnDisable()
void _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnDisable () inline private
Definition at line 27 of file PlanetBootstrap.cs.
        {
            if(settings != null) settings.OnSettingsChanged -= HandleSettingsChanged;
        }
References _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.HandleSettingsChanged(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.settings.
OnEnable()
void _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable () inline private
Definition at line 16 of file PlanetBootstrap.cs.
        {
            _planetManager = new PlanetManager(settings.config);
            _planetManager.RebuildOctree();
            if(settings != null) settings.OnSettingsChanged += HandleSettingsChanged;
            renderer.SetPlanetManager(_planetManager); // apply the chunk manager to the renderer
            Debug.Log("Planet manager set: " + _planetManager);
        }
References _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap._planetManager, _Project.World.Planet.Scripts.v2.Unity.PlanetSettings.config, _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.HandleSettingsChanged(), _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree(), _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.renderer, _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.SetPlanetManager(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.settings.
RebuildOctree()
void _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.RebuildOctree () inline
Definition at line 37 of file PlanetBootstrap.cs.
        {
            Debug.Log("Rebuilding Octree!! planet manager: " + _planetManager);
            _planetManager.RebuildOctree();
        }
References _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap._planetManager, and _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree().
Member Data Documentation
_planetManager
PlanetManager _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap._planetManager private
Definition at line 13 of file PlanetBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.HandleSettingsChanged(), _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.RebuildOctree().
renderer
new PlanetRenderer _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.renderer private
Definition at line 11 of file PlanetBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable().
settings
PlanetSettings _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.settings private
Definition at line 10 of file PlanetBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnDisable(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable().
The documentation for this class was generated from the following file:
World/Planet/Scripts/v2/Unity/PlanetBootstrap.cs