Openworld Factory (Name WIP): _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder Class Reference
_Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder Class Reference
Public Member Functions
MeshData Build ()
void AddTriangle (float3 a, float3 b, float3 c)
this adds a triangle to the mesh and calculates its indices and normals. this way you can just call this method for every triangle you want to add and it will take care of the rest.
void NormalizeNormals ()
this normalizes the normals. that means every normal has a length of exactly 1.
Private Member Functions
int GetOrAddVertex (float3 v)
checks if the given vertex already exists in the vertices list and if so returns its index, otherwise it adds it to the list and returns the new index
Static Private Member Functions
static float AngleBetween (float3 a, float3 b)
calculates the angle between 2 vectors
static int3 GetVertexKey (float3 v)
calculates a key based on the vertex position. it rounds on one decimal since thats smooth enough.
Private Attributes
readonly MeshData _meshData = new()
readonly Dictionary< int3, int > _vertexMap = new()
Detailed Description
Definition at line 6 of file MeshDataBuilder.cs.
Member Function Documentation
AddTriangle()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AddTriangle (float3 a, float3 b, float3 c) inline
this adds a triangle to the mesh and calculates its indices and normals. this way you can just call this method for every triangle you want to add and it will take care of the rest.
Definition at line 20 of file MeshDataBuilder.cs.
        {
            // Skip triangles with invalid or degenerate data to avoid NaN normals.
            if (!math.all(math.isfinite(a)) || !math.all(math.isfinite(b)) || !math.all(math.isfinite(c)))
            {
                return;
            }
            float3 ab = b - a;
            float3 ac = c - a;
            float3 normal = math.cross(ab, ac); // using the cross product of the 3 points we can get a rough estimation of the normals
            if (math.lengthsq(normal) < 1e-12f) // if the length of the normal is invalid there probably was a division through zero somewhere
                                                // so we just return (some really strange artifacts appear when there are vertices with NaN values in the mesh)
            {
                return;
            }
            int i0 = GetOrAddVertex(a);
            int i1 = GetOrAddVertex(b); // get or add the vertices and get their indices. this way we dont always generate new indices and since they connect their normals connect too and the results are smoother.
            int i2 = GetOrAddVertex(c);
            _meshData.Indices.Add(i0);
            _meshData.Indices.Add(i1); // add those indices to the mesh data
            _meshData.Indices.Add(i2);
            float angleA = AngleBetween(ab, ac);
            float angleB = AngleBetween(c - b, a - b); // we calculate the angles between the edges of the triangle and use them to weight the normals. this way we get better results for triangles that are not equilateral and avoid artifacts in sharp corners.
            float angleC = AngleBetween(a - c, b - c);
            float3 faceNormal = math.normalize(normal); // normalize the normal so it has a length of 1. this way we can use it to calculate the vertex normals by adding it to the corresponding vertices and then normalizing them at the end.
            _meshData.Normals[i0] += faceNormal * angleA;
            _meshData.Normals[i1] += faceNormal * angleB; // weight the normals by the angles to get better results for non-equilateral triangles
            _meshData.Normals[i2] += faceNormal * angleC;
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._meshData, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AngleBetween(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetOrAddVertex(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Indices, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Normals.
AngleBetween()
static float _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AngleBetween (float3 a, float3 b) inline static private
calculates the angle between 2 vectors
Parameters
a vector a
b vector b
Returns
the angle in radians
Definition at line 104 of file MeshDataBuilder.cs.
        {
            float len = math.length(a) * math.length(b); // get the length
            if (len < 1e-8f) // and check if its tiny, if it is we can skip the calculation since something that tiny will result in something even tinier and we can just return 0 to be more efficient
                return 0f;
            float d = math.clamp(math.dot(a, b) / len, -1f, 1f); // now just calculate the dot product and scale it down by the length.
                                                                 // due to floating point inaccuracies it can happen that the value is slightly above 1 or below -1 so we just clamp it.
            return math.acos(d); // finally we use acos to get the angle in radians
        }
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AddTriangle().
Build()
MeshData _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.Build ()
GetOrAddVertex()
int _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetOrAddVertex (float3 v) inline private
checks if the given vertex already exists in the vertices list and if so returns its index, otherwise it adds it to the list and returns the new index
Parameters
v the vertex to add or get
Definition at line 63 of file MeshDataBuilder.cs.
        {
            int3 vertexKey = GetVertexKey(v); // calculate the vertex key of that vertex
            if (_vertexMap.TryGetValue(vertexKey, out int index)) // if we already have a vertex with that key we return its index
                return index;
            index = _meshData.Vertices.Count; // otherwise we set the index to the current length of the vertices list
            _meshData.Vertices.Add(v); // and add that vertex
            _meshData.Normals.Add(float3.zero); // and normals
            _vertexMap.Add(vertexKey, index); // finally add it to the vertex map
            return index;
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._meshData, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._vertexMap, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetVertexKey(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Normals, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Vertices.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AddTriangle().
GetVertexKey()
static int3 _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetVertexKey (float3 v) static private
calculates a key based on the vertex position. it rounds on one decimal since thats smooth enough.
Parameters
v the vertex position
Returns
a 3d value to be used as a key
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetOrAddVertex().
NormalizeNormals()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.NormalizeNormals () inline
this normalizes the normals. that means every normal has a length of exactly 1.
Definition at line 83 of file MeshDataBuilder.cs.
        {
            for (int i = 0; i < _meshData.Normals.Count; i++)
            {
                float3 n = _meshData.Normals[i];
                if (!math.all(math.isfinite(n)) || math.lengthsq(n) < 1e-12f)
                {
                    _meshData.Normals[i] = new float3(0f, 1f, 0f);
                    continue;
                }
                _meshData.Normals[i] = math.normalize(n);
            }
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._meshData, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Normals.
Member Data Documentation
_meshData
readonly MeshData _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._meshData = new() private
Definition at line 8 of file MeshDataBuilder.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.AddTriangle(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetOrAddVertex(), and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.NormalizeNormals().
_vertexMap
readonly Dictionary<int3, int> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder._vertexMap = new() private
Definition at line 10 of file MeshDataBuilder.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshDataBuilder.GetOrAddVertex().
The documentation for this class was generated from the following file:
World/Planet/Scripts/MarchingCubes/MeshGeneration/MeshDataBuilder.cs