Openworld Factory (Name WIP): _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline Class Reference
_Project.World.Planet.Scripts.v2.ChunkGenerationPipeline Class Reference
Public Member Functions
void UpdateSamplerSettings (BurstSamplerSettings settings)
void UpdateMaxDepth (byte maxDepth)
void UpdateMin (int3 min)
void Update ()
void QueueGenerationAt (ulong mortonCode)
Events
Action< ChunkGeneration > OnChunkGenerated
Private Member Functions
void ProcessNextInQueue ()
void UpdateFinishedJobs ()
Private Attributes
readonly Queue< ulong > _generationQueue = new()
readonly Dictionary< ulong, JobHandle > _activeMeshingJobs = new()
readonly Dictionary< ulong, ChunkPayload > _activeMeshingJobResults = new()
BurstSamplerSettings _settings
byte _maxDepth
int3 _min
Detailed Description
Definition at line 13 of file ChunkGenerationPipeline.cs.
Member Function Documentation
ProcessNextInQueue()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue () inline private
Definition at line 53 of file ChunkGenerationPipeline.cs.
        {
            if (_generationQueue.Count == 0) return;
            ulong mortonCode = _generationQueue.Dequeue();
            const byte resolution = 32;
            JobHandle densityJobHandle = DensityFieldBuilder.ScheduleBurstDensityFieldDataBuildInTree(
                _settings,
                mortonCode,
                _maxDepth,
                _min,
                resolution,
                out DensityFieldData densityField
            );
            JobHandle meshGenerationJobHandle = BurstMeshGenerator.ScheduleGenerateMesh(densityJobHandle, densityField,
                out NativeList<int> indices, out NativeList<float3> vertices, out NativeList<float3> normals);
            ChunkPayload payload = new ChunkPayload
            {
                DensityField = densityField,
                Vertices = vertices.ToArray(Allocator.Persistent),
                Normals = normals.ToArray(Allocator.Persistent), // todo check if keeping it as lists is more performant
                Indices = indices.ToArray(Allocator.Persistent),
            };
            _activeMeshingJobs.Add(mortonCode, meshGenerationJobHandle);
            _activeMeshingJobResults.Add(mortonCode, payload);
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobResults, _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobs, _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._generationQueue, _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._maxDepth, _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._min, and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._settings.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.Update().
QueueGenerationAt()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.QueueGenerationAt (ulong mortonCode) inline
Definition at line 48 of file ChunkGenerationPipeline.cs.
        {
            _generationQueue.Enqueue(mortonCode);
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._generationQueue.
Update()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.Update () inline
Definition at line 42 of file ChunkGenerationPipeline.cs.
        {
            ProcessNextInQueue();
            UpdateFinishedJobs();
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateFinishedJobs().
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.Update().
UpdateFinishedJobs()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateFinishedJobs () inline private
Definition at line 86 of file ChunkGenerationPipeline.cs.
        {
            foreach (ulong mortonCode in _activeMeshingJobs.Keys)
            {
                if (!_activeMeshingJobs.TryGetValue(mortonCode, out JobHandle jobHandle)) continue;
                bool completed = jobHandle.IsCompleted;
                if (!completed) continue;
                jobHandle.Complete();
                OnChunkGenerated?.Invoke(new ChunkGeneration
                {
                    Payload = _activeMeshingJobResults[mortonCode],
                    MortonCode = mortonCode
                });
                _activeMeshingJobs.Remove(mortonCode);
                _activeMeshingJobResults.Remove(mortonCode);
            }
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobResults, _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobs, and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.OnChunkGenerated.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.Update().
UpdateMaxDepth()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMaxDepth (byte maxDepth) inline
Definition at line 31 of file ChunkGenerationPipeline.cs.
        {
            _maxDepth = maxDepth;
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._maxDepth.
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree().
UpdateMin()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMin (int3 min) inline
Definition at line 36 of file ChunkGenerationPipeline.cs.
        {
            _min = min;
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._min.
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.UpdateConfig().
UpdateSamplerSettings()
void _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateSamplerSettings (BurstSamplerSettings settings) inline
Definition at line 26 of file ChunkGenerationPipeline.cs.
        {
            _settings = settings;
        }
References _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._settings.
Member Data Documentation
_activeMeshingJobResults
readonly Dictionary<ulong, ChunkPayload> _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobResults = new() private
Definition at line 17 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateFinishedJobs().
_activeMeshingJobs
readonly Dictionary<ulong, JobHandle> _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._activeMeshingJobs = new() private
Definition at line 16 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateFinishedJobs().
_generationQueue
readonly Queue<ulong> _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._generationQueue = new() private
Definition at line 15 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.QueueGenerationAt().
_maxDepth
byte _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._maxDepth private
Definition at line 20 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMaxDepth().
_min
int3 _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._min private
Definition at line 21 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMin().
_settings
BurstSamplerSettings _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline._settings private
Definition at line 19 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.ProcessNextInQueue(), and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateSamplerSettings().
Event Documentation
OnChunkGenerated
Action<ChunkGeneration> _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.OnChunkGenerated
Definition at line 23 of file ChunkGenerationPipeline.cs.
Referenced by _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateFinishedJobs().
The documentation for this class was generated from the following file:
World/Planet/Scripts/v2/ChunkGenerationPipeline.cs