Openworld Factory (Name WIP): _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem Class Reference
_Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem Class Reference
Public Member Functions
void Update (Octree octree, Camera camera)
Public Attributes
readonly List< ulong > VisibleChunks = new()
Private Member Functions
void UpdateVisibleChunks (Octree octree, Camera camera)
void Traverse (Octree octree, ulong mortonCode, Plane[] planes)
bool NeedsUpdate (Camera camera)
Static Private Member Functions
static bool IsVisible (Bounds bounds, Plane[] planes)
Private Attributes
Vector3 _lastPosition
Quaternion _lastRotation
Static Private Attributes
const float PositionThreshold = 2f
const float RotationThreshold = 2f
Detailed Description
Definition at line 8 of file FrustumCullingSystem.cs.
Member Function Documentation
IsVisible()
static bool _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.IsVisible (Bounds bounds, Plane[] planes) inline static private
Definition at line 90 of file FrustumCullingSystem.cs.
        {
            foreach (Plane plane in planes)
            {
                Vector3 normal = plane.normal;
                Vector3 p = bounds.min;
                if (normal.x >= 0) p.x = bounds.max.x;
                if (normal.y >= 0) p.y = bounds.max.y;
                if (normal.z >= 0) p.z = bounds.max.z;
                if (plane.GetDistanceToPoint(p) < 0)
                    return false;
            }
            return true;
        }
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse().
NeedsUpdate()
bool _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate (Camera camera) inline private
Definition at line 112 of file FrustumCullingSystem.cs.
        {
            float positionDelta =
                Vector3.Distance(
                    camera.transform.position,
                    _lastPosition);
            float rotationDelta =
                Quaternion.Angle(
                    camera.transform.rotation,
                    _lastRotation);
            return positionDelta > PositionThreshold ||
                   rotationDelta > RotationThreshold;
        }
References _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastPosition, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastRotation, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.PositionThreshold, and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.RotationThreshold.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update().
Traverse()
void _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse (Octree octree, ulong mortonCode, Plane[] planes) inline private
Definition at line 50 of file FrustumCullingSystem.cs.
        {
            OctreeNode? nodeNullable =
                octree.GetNodeAtPosition(mortonCode);
            if (!nodeNullable.HasValue)
                return;
            OctreeNode node = nodeNullable.Value;
            Bounds bounds =
                octree.GetBounds(mortonCode);
            if (!IsVisible(bounds, planes))
                return;
            bool isLeaf = node.ChildMask == 0;
            if (isLeaf)
            {
                VisibleChunks.Add(mortonCode);
                return;
            }
            for (byte i = 0; i < 8; i++)
            {
                if ((node.ChildMask & (1 << i)) == 0)
                    continue;
                Traverse(
                    octree,
                    mortonCode.AppendChild(i),
                    planes
                );
            }
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.OctreeNode.ChildMask, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.IsVisible(), _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.VisibleChunks.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.UpdateVisibleChunks().
Update()
void _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update (Octree octree, Camera camera) inline
Definition at line 19 of file FrustumCullingSystem.cs.
        {
            if (!NeedsUpdate(camera))
                return;
            UpdateVisibleChunks(octree, camera);
            _lastPosition = camera.transform.position;
            _lastRotation = camera.transform.rotation;
        }
References _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastPosition, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastRotation, _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.UpdateVisibleChunks().
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update().
UpdateVisibleChunks()
void _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.UpdateVisibleChunks (Octree octree, Camera camera) inline private
Definition at line 32 of file FrustumCullingSystem.cs.
        {
            VisibleChunks.Clear();
            Plane[] planes =
                GeometryUtility.CalculateFrustumPlanes(camera);
            Traverse(
                octree,
                new int3(0,0,0).EncodeToMorton(0),
                planes
            );
            Debug.Log("Updated, new amount of visible chunks: " + VisibleChunks.Count);
        }
References _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.VisibleChunks.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update().
Member Data Documentation
_lastPosition
Vector3 _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastPosition private
Definition at line 12 of file FrustumCullingSystem.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update().
_lastRotation
Quaternion _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem._lastRotation private
Definition at line 13 of file FrustumCullingSystem.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Update().
PositionThreshold
const float _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.PositionThreshold = 2f static private
Definition at line 15 of file FrustumCullingSystem.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate().
RotationThreshold
const float _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.RotationThreshold = 2f static private
Definition at line 17 of file FrustumCullingSystem.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.NeedsUpdate().
VisibleChunks
readonly List<ulong> _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.VisibleChunks = new()
Definition at line 10 of file FrustumCullingSystem.cs.
Referenced by _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.Traverse(), and _Project.World.Planet.Scripts.v2.Rendering.FrustumCullingSystem.UpdateVisibleChunks().
The documentation for this class was generated from the following file:
World/Planet/Scripts/v2/Rendering/FrustumCullingSystem.cs