Openworld Factory (Name WIP): _Project.World.Planet.Scripts.v2.PlanetManager Class Reference
_Project.World.Planet.Scripts.v2.PlanetManager Class Reference
Public Member Functions
PlanetManager (PlanetConfig config)
void RebuildOctree ()
void Update ()
void UpdateConfig (PlanetConfig config)
void SplitChunkAt (ulong mortonCode)
void MergeChunkAt (ulong mortonCode)
void Dispose ()
Properties
Octree Octree [get, private set]
bool OctreeReady [get, private set]
Private Member Functions
void OnChunkGenerated (ChunkGeneration chunkGeneration)
Private Attributes
PlanetConfig _config
ChunkDataStore _chunkDataStore
ChunkGenerationPipeline _chunkGenerationPipeline
Detailed Description
Definition at line 8 of file PlanetManager.cs.
Constructor & Destructor Documentation
PlanetManager()
_Project.World.Planet.Scripts.v2.PlanetManager.PlanetManager (PlanetConfig config) inline
Definition at line 18 of file PlanetManager.cs.
        {
            _config = config;
            _chunkGenerationPipeline = new ChunkGenerationPipeline();
            _chunkGenerationPipeline.OnChunkGenerated += OnChunkGenerated;
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._chunkGenerationPipeline, _Project.World.Planet.Scripts.v2.PlanetManager._config, and _Project.World.Planet.Scripts.v2.PlanetManager.OnChunkGenerated().
Member Function Documentation
Dispose()
void _Project.World.Planet.Scripts.v2.PlanetManager.Dispose () inline
Definition at line 60 of file PlanetManager.cs.
        {
            Octree.Dispose();
            _chunkGenerationPipeline.OnChunkGenerated -= OnChunkGenerated;
        }
References _Project.World.Planet.Scripts.v2.PlanetManager.OnChunkGenerated().
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.OnDestroy().
MergeChunkAt()
void _Project.World.Planet.Scripts.v2.PlanetManager.MergeChunkAt (ulong mortonCode) inline
Definition at line 50 of file PlanetManager.cs.
        {
            Octree.Merge(mortonCode);
        }
OnChunkGenerated()
void _Project.World.Planet.Scripts.v2.PlanetManager.OnChunkGenerated (ChunkGeneration chunkGeneration) inline private
Definition at line 55 of file PlanetManager.cs.
        {
            _chunkDataStore.SetChunkPayloadAt(chunkGeneration.MortonCode, chunkGeneration.Payload);
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._chunkDataStore, _Project.World.Planet.Scripts.v2.ChunkGeneration.MortonCode, _Project.World.Planet.Scripts.v2.ChunkGeneration.Payload, and _Project.World.Planet.Scripts.v2.Data.ChunkDataStore.SetChunkPayloadAt().
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.Dispose(), and _Project.World.Planet.Scripts.v2.PlanetManager.PlanetManager().
RebuildOctree()
void _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree () inline
Definition at line 26 of file PlanetManager.cs.
        {
            Octree = OctreeHelper.Build(_config.origin, _config.origin + new int3(_config.size), _config.samplerSettings, 1);
            _chunkGenerationPipeline.UpdateMaxDepth(Octree.MaxDepth);
            OctreeReady = true;
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._chunkGenerationPipeline, _Project.World.Planet.Scripts.v2.PlanetManager._config, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.Octree.MaxDepth, _Project.World.Planet.Scripts.v2.PlanetManager.OctreeReady, _Project.World.Planet.Scripts.v2.Unity.PlanetConfig.origin, _Project.World.Planet.Scripts.v2.Unity.PlanetConfig.samplerSettings, _Project.World.Planet.Scripts.v2.Unity.PlanetConfig.size, and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMaxDepth().
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.OnEnable(), and _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.RebuildOctree().
SplitChunkAt()
void _Project.World.Planet.Scripts.v2.PlanetManager.SplitChunkAt (ulong mortonCode) inline
Definition at line 45 of file PlanetManager.cs.
        {
            Octree.Split(mortonCode, _config.samplerSettings);
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._config, and _Project.World.Planet.Scripts.v2.Unity.PlanetConfig.samplerSettings.
Update()
void _Project.World.Planet.Scripts.v2.PlanetManager.Update () inline
Definition at line 33 of file PlanetManager.cs.
        {
            _chunkGenerationPipeline.Update();
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._chunkGenerationPipeline, and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.Update().
UpdateConfig()
void _Project.World.Planet.Scripts.v2.PlanetManager.UpdateConfig (PlanetConfig config) inline
Definition at line 39 of file PlanetManager.cs.
        {
            _config = config;
            _chunkGenerationPipeline.UpdateMin(config.origin);
        }
References _Project.World.Planet.Scripts.v2.PlanetManager._chunkGenerationPipeline, _Project.World.Planet.Scripts.v2.PlanetManager._config, _Project.World.Planet.Scripts.v2.Unity.PlanetConfig.origin, and _Project.World.Planet.Scripts.v2.ChunkGenerationPipeline.UpdateMin().
Referenced by _Project.World.Planet.Scripts.v2.Unity.PlanetBootstrap.HandleSettingsChanged().
Member Data Documentation
_chunkDataStore
ChunkDataStore _Project.World.Planet.Scripts.v2.PlanetManager._chunkDataStore private
Definition at line 14 of file PlanetManager.cs.
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.OnChunkGenerated().
_chunkGenerationPipeline
ChunkGenerationPipeline _Project.World.Planet.Scripts.v2.PlanetManager._chunkGenerationPipeline private
Definition at line 16 of file PlanetManager.cs.
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.PlanetManager(), _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree(), _Project.World.Planet.Scripts.v2.PlanetManager.Update(), and _Project.World.Planet.Scripts.v2.PlanetManager.UpdateConfig().
_config
PlanetConfig _Project.World.Planet.Scripts.v2.PlanetManager._config private
Definition at line 10 of file PlanetManager.cs.
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.PlanetManager(), _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree(), _Project.World.Planet.Scripts.v2.PlanetManager.SplitChunkAt(), and _Project.World.Planet.Scripts.v2.PlanetManager.UpdateConfig().
Property Documentation
Octree
Octree _Project.World.Planet.Scripts.v2.PlanetManager.Octree get private set
Definition at line 13 of file PlanetManager.cs.
{ get; private set; }
Referenced by _Project.World.Planet.Scripts.v2.Rendering.PlanetRenderer.Update().
OctreeReady
bool _Project.World.Planet.Scripts.v2.PlanetManager.OctreeReady get private set
Definition at line 25 of file PlanetManager.cs.
{get; private set; }
Referenced by _Project.World.Planet.Scripts.v2.PlanetManager.RebuildOctree().
The documentation for this class was generated from the following file:
World/Planet/Scripts/v2/PlanetManager.cs