Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap Class Reference
_Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap Class Reference
Public Member Functions
void RebuildChunks ()
Private Member Functions
void OnEnable ()
void OnDisable ()
Private Attributes
OctreeChunkSystemSettings settings
new OctreeChunkSystemRenderer renderer
Transform viewer
OctreeChunkManager _chunkManager
Detailed Description
Definition at line 7 of file OctreeChunkSystemBootstrap.cs.
Member Function Documentation
OnDisable()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnDisable () inline private
Definition at line 38 of file OctreeChunkSystemBootstrap.cs.
        {
            if (renderer != null) // if there is a renderer assigned we need to dispose it and its components to prevent memory leaks and other issues
            {
                renderer.SetChunkManager(null); // "remove" the chunk manager
            }
            _chunkManager = null; // remove the chunk manager object reference
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap._chunkManager, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.renderer, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.SetChunkManager().
OnEnable()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnEnable () inline private
Definition at line 15 of file OctreeChunkSystemBootstrap.cs.
        {
            if (renderer == null) // only add a renderer if the current one is not set
            {
                renderer = GetComponent<OctreeChunkSystemRenderer>();
            }
            if (settings == null) // the user has to specify the settings themselves so if the settings arent specified when the object is instantiated we throw an error
            {
                Debug.LogError("OctreeChunkSystemSettings is missing.", this);
                return;
            }
            if (renderer == null) // same goes for the renderer
            {
                Debug.LogError("OctreeChunkSystemRenderer is missing.", this);
                return;
            }
            _chunkManager = settings.CreateManager(); // create the chunk manager based on the settings. this is where the logic of the chunk system is being created.
            renderer.SetChunkManager(_chunkManager); // apply the chunk manager to the renderer
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap._chunkManager, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemSettings.CreateManager(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.renderer, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.SetChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.settings.
RebuildChunks()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.RebuildChunks () inline
Definition at line 48 of file OctreeChunkSystemBootstrap.cs.
        {
            _chunkManager.Origin = new int3(settings.origin.x, settings.origin.y, settings.origin.z);
            _chunkManager.Size = settings.size;
            _chunkManager.RebuildOctree();
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap._chunkManager, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemSettings.origin, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.settings, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemSettings.size.
Member Data Documentation
_chunkManager
OctreeChunkManager _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap._chunkManager private
Definition at line 13 of file OctreeChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnDisable(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnEnable(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.RebuildChunks().
renderer
new OctreeChunkSystemRenderer _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.renderer private
Definition at line 10 of file OctreeChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnEnable().
settings
OctreeChunkSystemSettings _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.settings private
Definition at line 9 of file OctreeChunkSystemBootstrap.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnEnable(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.RebuildChunks().
viewer
Transform _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.viewer private
Definition at line 11 of file OctreeChunkSystemBootstrap.cs.
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/OctreeChunkSystem/Unity/OctreeChunkSystemBootstrap.cs