Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer Class Reference
_Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer Class Reference
Public Member Functions
void SetChunkManager (OctreeChunkManager chunkManager)
void OnDrawGizmos ()
Private Member Functions
void OnChunkChange (NodeChange chunkChange)
void Update ()
Private Attributes
OctreeChunkManager _chunkManager
Transform _viewer
readonly Queue< NodeChange > _chunkChanges = new()
byte octreeGizmoDrawLayer = 0
Detailed Description
Definition at line 10 of file OctreeChunkSystemRenderer.cs.
Member Function Documentation
OnChunkChange()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnChunkChange (NodeChange chunkChange) inline private
Definition at line 32 of file OctreeChunkSystemRenderer.cs.
        {
            _chunkChanges.Enqueue(chunkChange);
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkChanges.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.SetChunkManager().
OnDrawGizmos()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnDrawGizmos () inline
Definition at line 37 of file OctreeChunkSystemRenderer.cs.
        {
            Octree octree = _chunkManager.Octree;
            float3 rootSize = octree.Max - octree.Min;
            foreach (OctreeNode octreeNode in _chunkManager.Octree.Nodes)
            {
                if (octreeNode.Depth > octreeGizmoDrawLayer) continue;
                Gizmos.color = Color.Lerp(Color.white, Color.red, (float) octreeNode.Depth / octreeGizmoDrawLayer);
                int3 min = octreeNode.Coord;
                float3 size = rootSize / (1 << octreeNode.Depth);
                Gizmos.DrawWireCube(min + size/2, size);
                if (octreeNode.Depth != octreeGizmoDrawLayer) continue;
                switch (octreeNode.State)
                {
                    case OctreeNodeState.Empty: Gizmos.color = Color.purple.WithAlpha(0.2f); break;
                    case OctreeNodeState.Full: Gizmos.color = Color.green; break;
                    case OctreeNodeState.Mixed: Gizmos.color = Color.yellow.WithAlpha(0.6f); break;
                    case OctreeNodeState.Unknown: Gizmos.color = Color.blue; break;
                }
                Gizmos.DrawCube(min + size / 2, size/5);
            }
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkManager, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.OctreeNode.Coord, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.OctreeNode.Depth, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.Octree.Min, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.Octree.Nodes, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Octree, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.octreeGizmoDrawLayer, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Core.OctreeNode.State.
SetChunkManager()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.SetChunkManager (OctreeChunkManager chunkManager) inline
Definition at line 20 of file OctreeChunkSystemRenderer.cs.
        {
            // unsubscribe old
            if (_chunkManager != null)
                _chunkManager.NodeChange -= OnChunkChange;
            _chunkManager = chunkManager;
            if (_chunkManager != null)
                _chunkManager.NodeChange += OnChunkChange;
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkManager, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnChunkChange().
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.OnEnable().
Update()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.Update () inline private
Definition at line 67 of file OctreeChunkSystemRenderer.cs.
        {
            float3 viewerPosition = _viewer != null ? _viewer.position : float3.zero;
            _chunkManager?.Update(viewerPosition);
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkManager, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._viewer, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Update().
Member Data Documentation
_chunkChanges
readonly Queue<NodeChange> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkChanges = new() private
Definition at line 16 of file OctreeChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnChunkChange().
_chunkManager
OctreeChunkManager _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._chunkManager private
Definition at line 12 of file OctreeChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnDrawGizmos(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.SetChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.Update().
_viewer
Transform _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer._viewer private
Definition at line 14 of file OctreeChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.Update().
octreeGizmoDrawLayer
byte _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.octreeGizmoDrawLayer = 0 private
Definition at line 18 of file OctreeChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnDrawGizmos().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/OctreeChunkSystem/Unity/OctreeChunkSystemRenderer.cs