Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer Class Reference
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer Class Reference
Public Member Functions
void SetChunkManager (GridChunkManager chunkManager)
void SetViewer (Transform viewer)
Private Member Functions
void OnChunkChange (ChunkChange chunkChange)
void Awake ()
void RebuildRendererDictionary ()
void Update ()
void SyncRenderers ()
void CreateRendererAt (ChunkCoord loadedChunkCoord)
void DestroyRendererAt (ChunkCoord loadedChunkCoord)
void UpdateRendererAt (ChunkCoord loadedChunkCoord)
Private Attributes
GridChunkManager _chunkManager
Transform _viewer
readonly Dictionary< ChunkCoord, ChunkRenderer > _chunkRenderers = new()
readonly Queue< ChunkChange > _chunkChanges = new()
Detailed Description
Definition at line 9 of file GridChunkSystemRenderer.cs.
Member Function Documentation
Awake()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Awake () inline private
Definition at line 39 of file GridChunkSystemRenderer.cs.
        {
            RebuildRendererDictionary();
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.RebuildRendererDictionary().
CreateRendererAt()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt (ChunkCoord loadedChunkCoord) inline private
Definition at line 91 of file GridChunkSystemRenderer.cs.
        {
            MeshData meshData =
                _chunkManager.GetChunkAt(loadedChunkCoord)?.MeshData;
            if(meshData == null) return;
            GameObject go = new($"Chunk_{loadedChunkCoord}")
            {
                transform =
                {
                    parent = transform
                }
            };
            int3 worldPos = (loadedChunkCoord.Value * _chunkManager.ChunkSize);
            go.transform.position = new Vector3(worldPos.x, worldPos.y, worldPos.z);
            ChunkRenderer chunkRenderer =
                go.AddComponent<ChunkRenderer>();
            Mesh unityMesh = UnityMeshBuilder.Build(meshData);
            meshData.Dispose();
            chunkRenderer.ApplyMeshData(unityMesh);
            _chunkRenderers.Add(loadedChunkCoord, chunkRenderer);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkManager, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkRenderers, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.ApplyMeshData(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkSize, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Dispose(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetChunkAt(), and _Project.World.Planet.Scripts.Chunking.Core.ChunkData.MeshData.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers().
DestroyRendererAt()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.DestroyRendererAt (ChunkCoord loadedChunkCoord) inline private
Definition at line 124 of file GridChunkSystemRenderer.cs.
        {
            ChunkRenderer chunkRenderer = _chunkRenderers[loadedChunkCoord];
            Destroy(chunkRenderer.gameObject);
            _chunkRenderers.Remove(loadedChunkCoord);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkRenderers.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers().
OnChunkChange()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.OnChunkChange (ChunkChange chunkChange) inline private
Definition at line 34 of file GridChunkSystemRenderer.cs.
        {
            _chunkChanges.Enqueue(chunkChange);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkChanges.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetChunkManager().
RebuildRendererDictionary()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.RebuildRendererDictionary () inline private
Definition at line 45 of file GridChunkSystemRenderer.cs.
        {
            _chunkRenderers.Clear();
            ChunkRenderer[] renderers =
                GetComponentsInChildren<ChunkRenderer>();
            foreach (var chunkRenderer in renderers)
            {
                string rendererName = chunkRenderer.gameObject.name;
                ChunkCoord coord = ChunkCoord.ParseChunkCoord(rendererName);
                _chunkRenderers[coord] = chunkRenderer;
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkRenderers, and _Project.World.Planet.Scripts.Chunking.Core.ChunkCoord.ParseChunkCoord().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Awake().
SetChunkManager()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetChunkManager (GridChunkManager chunkManager) inline
Definition at line 17 of file GridChunkSystemRenderer.cs.
        {
            // unsubscribe old
            if (_chunkManager != null)
                _chunkManager.ChunkChange -= OnChunkChange;
            _chunkManager = chunkManager;
            if (_chunkManager != null)
                _chunkManager.ChunkChange += OnChunkChange;
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkManager, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.OnChunkChange().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
SetViewer()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetViewer (Transform viewer) inline
Definition at line 29 of file GridChunkSystemRenderer.cs.
        {
            _viewer = viewer;
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._viewer.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnDisable(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.Unity.GridChunkSystemBootstrap.OnEnable().
SyncRenderers()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers () inline private
Definition at line 70 of file GridChunkSystemRenderer.cs.
        {
            while (_chunkChanges.Count > 0)
            {
                ChunkChange chunkChange = _chunkChanges.Dequeue();
                switch (chunkChange.Type)
                {
                    case ChunkChangeType.Load:
                        CreateRendererAt(chunkChange.Coord);
                        break;
                    case ChunkChangeType.Unload:
                        DestroyRendererAt(chunkChange.Coord);
                        break;
                    case ChunkChangeType.Update:
                        UpdateRendererAt(chunkChange.Coord);
                        break;
                }
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkChanges, _Project.World.Planet.Scripts.Chunking.Core.ChunkChange.Coord, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.DestroyRendererAt(), _Project.World.Planet.Scripts.Chunking.Core.ChunkChange.Type, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Update().
Update()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Update () inline private
Definition at line 62 of file GridChunkSystemRenderer.cs.
        {
            float3 viewerPosition = _viewer != null ? _viewer.position : float3.zero;
            _chunkManager?.Update(viewerPosition);
            SyncRenderers();
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkManager, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._viewer, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.Update().
UpdateRendererAt()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt (ChunkCoord loadedChunkCoord) inline private
Definition at line 131 of file GridChunkSystemRenderer.cs.
        {
            ChunkRenderer chunkRenderer = _chunkRenderers[loadedChunkCoord];
            MeshData meshData = _chunkManager.GetChunkAt(loadedChunkCoord)?.MeshData;
            if (meshData == null) return;
            Mesh unityMesh = UnityMeshBuilder.Build(meshData);
            meshData.Dispose(); // we can dispose the mesh data after building the unity mesh since we don't need it anymore. this is important to avoid memory leaks since the mesh data uses native collections that are not managed by the garbage collector.
            chunkRenderer.ApplyMeshData(unityMesh);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkManager, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkRenderers, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.ApplyMeshData(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.MeshData.Dispose(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetChunkAt(), and _Project.World.Planet.Scripts.Chunking.Core.ChunkData.MeshData.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers().
Member Data Documentation
_chunkChanges
readonly Queue<ChunkChange> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkChanges = new() private
Definition at line 15 of file GridChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.OnChunkChange(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SyncRenderers().
_chunkManager
GridChunkManager _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkManager private
Definition at line 11 of file GridChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetChunkManager(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Update(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt().
_chunkRenderers
readonly Dictionary<ChunkCoord, ChunkRenderer> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._chunkRenderers = new() private
Definition at line 14 of file GridChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.DestroyRendererAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.RebuildRendererDictionary(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt().
_viewer
Transform _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer._viewer private
Definition at line 12 of file GridChunkSystemRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.SetViewer(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Update().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/GridChunkSystem/GridChunkSystemRenderer.cs