Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager Class Reference
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager Class Reference
this is the core of the logic of this system. the grid chunk manager is responsible for managing the chunks states, generating the chunks and loading / unloading them.
Public Member Functions
GridChunkManager (int chunkSize, int viewDistanceInChunks, BurstSamplerSettings densitySamplerSettings)
ChunkData GetChunkAt (ChunkCoord coord)
returns the chunk data of a given position. if no chunk exists at that position, null is returned.
IEnumerable< ChunkCoord > GetLoadedChunkCoords ()
returns the coordinates of the currently loaded chunks
void Update (float3 viewerPosition)
updates the chunk manager. this should be called once per frame. it processes the completed chunk generations, syncs the loaded chunks with the viewers position and processes the load / unload queues. this should only be called by the renderer as it is inefficient to update the manager multiple times per frame as it only changes across frames and not within a single frame.
Public Attributes
readonly int ChunkSize
Events
Action< ChunkChange > ChunkChange
Private Member Functions
void ProcessQueues ()
loads / unloads chunks if they are in the different queueues. it doesnt check what chunks need to be loaded / unloaded!
void SyncChunks (float3 viewerPosition)
syncs the loaded chunks with the viewers position. it calculates what chunks should be loaded based on the viewers position and the view distance and adds those to the load queue if they are not already loaded. it also calculates what chunks should be unloaded and adds those to the unload queue if they are currently loaded. it does not actually loads or unloads the chunks, the processQueues method is responsible for that.
async Task GenerateChunkAsync (ChunkCoord coord)
generates a chunk at a given position using the chunk generator
void ProcessCompletedChunks ()
processes the completed chunk generations. it shifts the generated data from the _completedChunks queue to the main _chunks and _chunkStates dictionaries and triggers the chunk change event for the loaded chunks. this should only be called in the main thread (like in the update method) as it accesses the main dictionaries that are not thread safe.
void UnloadChunk (ChunkCoord coord)
unloads the chunk at a given position
Private Attributes
readonly Dictionary< ChunkCoord, ChunkData > _chunks = new()
readonly Dictionary< ChunkCoord, ChunkLifecycleState > _chunkStates = new()
readonly Queue< ChunkCoord > _loadQueue
readonly Queue< ChunkCoord > _unloadQueue = new()
readonly ConcurrentQueue<(ChunkCoord coord, ChunkData data)> _completedChunks
readonly ChunkGenerator _chunkGenerator
readonly ChunkStreamer _chunkStreamer
int3 _lastViewerChunk
bool _hasLastViewerChunk
int _activeGenerationTasks
readonly int _viewDistanceInChunks
Static Private Attributes
const int ChunksPerFrame = 20
const int MaxConcurrentGenerationTasks = 8
Detailed Description
this is the core of the logic of this system. the grid chunk manager is responsible for managing the chunks states, generating the chunks and loading / unloading them.
Definition at line 16 of file GridChunkManager.cs.
Constructor & Destructor Documentation
GridChunkManager()
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GridChunkManager (int chunkSize, int viewDistanceInChunks, BurstSamplerSettings densitySamplerSettings) inline
Parameters
chunkSize the chunk size
viewDistanceInChunks the view distance of the viewer, acting as a radius of the sphere of included chunks around the viewer
densitySamplerSettings the settings used for generating the density values
Definition at line 58 of file GridChunkManager.cs.
        {
            ChunkSize = chunkSize;
            _viewDistanceInChunks = viewDistanceInChunks;
            _chunkGenerator = new ChunkGenerator(
                densitySamplerSettings,
                chunkSize
            );
            _chunkStreamer = new ChunkStreamer(chunkSize);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkGenerator, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStreamer, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._viewDistanceInChunks, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkSize.
Member Function Documentation
GenerateChunkAsync()
async Task _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync (ChunkCoord coord) inline private
generates a chunk at a given position using the chunk generator
Parameters
coord the coordinate of the chunk that gets generated
Definition at line 210 of file GridChunkManager.cs.
        {
            Interlocked.Increment(ref _activeGenerationTasks); // keep track of the current amount of chunks that are being generated since they can generate across multiple frames
            _chunkStates[coord] = ChunkLifecycleState.Generating; // set the current state to generating
            try
            {
                ChunkData chunkData = await Task.Run(() => _chunkGenerator.GenerateChunkAt(coord)); // run the generation job
                _completedChunks.Enqueue((coord, chunkData)); // and add its data afterward.
                                                              // this _completedChunks queue will get processed in the main thread in the update method to shift the
                                                              // generated data over to the main dictionaries and trigger the chunk change event
            }
            catch (Exception e)
            {
                Debug.LogException(e);
            }
            finally
            {
                Interlocked.Decrement(ref _activeGenerationTasks); // and finally (even if the task failed) remove it from the active tasks count
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._activeGenerationTasks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkGenerator, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStates, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._completedChunks, and _Project.World.Planet.Scripts.Chunking.ChunkGenerator.GenerateChunkAt().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues().
GetChunkAt()
ChunkData _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetChunkAt (ChunkCoord coord) inline
returns the chunk data of a given position. if no chunk exists at that position, null is returned.
Parameters
coord the coordinate of the chunk
Returns
the chunk data of the chunk at that position. may be null.
Definition at line 80 of file GridChunkManager.cs.
        {
            return _chunks.GetValueOrDefault(coord, null);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt().
GetLoadedChunkCoords()
IEnumerable< ChunkCoord > _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetLoadedChunkCoords () inline
returns the coordinates of the currently loaded chunks
Returns
the chunk coordinates of the currently loaded chunks
Definition at line 89 of file GridChunkManager.cs.
        {
            return _chunks.Keys;
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks.
ProcessCompletedChunks()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks () inline private
processes the completed chunk generations. it shifts the generated data from the _completedChunks queue to the main _chunks and _chunkStates dictionaries and triggers the chunk change event for the loaded chunks. this should only be called in the main thread (like in the update method) as it accesses the main dictionaries that are not thread safe.
Definition at line 239 of file GridChunkManager.cs.
        {
            while (_completedChunks.TryDequeue(out var result)) // every completed chunk gets processed
            {
                ChunkCoord coord = result.coord;
                ChunkData data = result.data;
                if (!_chunkStates.TryGetValue(coord, out var state)) // if the state of the chunk doesnt exist, its broken as the state is already generated before starting the generation task. so to prevent further errors we just ignore that case
                    continue;
                if (state != ChunkLifecycleState.Generating) // the state should currently be in the "generating" phase
                    continue;
                _chunks[coord] = data; // apply the data to the main chunks dictionary
                _chunkStates[coord] = ChunkLifecycleState.Loaded; // and update the state to loaded
                ChunkChange?.Invoke( // report the change to the listeners
                    new ChunkChange(coord, ChunkChangeType.Load)
                );
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStates, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._completedChunks, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkChange.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.Update().
ProcessQueues()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues () inline private
loads / unloads chunks if they are in the different queueues. it doesnt check what chunks need to be loaded / unloaded!
Definition at line 112 of file GridChunkManager.cs.
        {
            int chunkCounter = 0; // counts the chunks we loaded or unloaded in this frame
            while
                (chunkCounter <
                 ChunksPerFrame) // we only want to load / unload a certain amount of chunks per frame to avoid performance spikes
            {
                if (_unloadQueue.Count <= 0) // break the loop if there are no more chunks to unload
                    break;
                ChunkCoord coord = _unloadQueue.Dequeue(); // retrieve a chunk coord to unload from the queue
                UnloadChunk(coord);
                chunkCounter++;
            }
            while
                (chunkCounter <
                 ChunksPerFrame) // we reuse the chunk counter without resetting it to ensure we only do a limited amount of operations (not loads and unloads) per frame
            {
                if (_activeGenerationTasks >=
                    MaxConcurrentGenerationTasks) // break if we cant start any more tasks this frame
                    break;
                if (_loadQueue.Count <= 0) // or break if the queue is empty
                    break;
                ChunkCoord coord = _loadQueue.Dequeue();
                _ = GenerateChunkAsync(
                    coord); // we dont need the result of the task as its already automatically getting stored, but we need to add a reference to the task for it to start so we just use a tmp variable
                chunkCounter++;
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._activeGenerationTasks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._loadQueue, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._unloadQueue, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunksPerFrame, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.MaxConcurrentGenerationTasks, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.UnloadChunk().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.Update().
SyncChunks()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks (float3 viewerPosition) inline private
syncs the loaded chunks with the viewers position. it calculates what chunks should be loaded based on the viewers position and the view distance and adds those to the load queue if they are not already loaded. it also calculates what chunks should be unloaded and adds those to the unload queue if they are currently loaded. it does not actually loads or unloads the chunks, the processQueues method is responsible for that.
Parameters
viewerPosition
Definition at line 156 of file GridChunkManager.cs.
        {
            int3 viewerChunk =
                (int3)math.floor(viewerPosition / ChunkSize); // convert world to chunk space
            if (_hasLastViewerChunk && viewerChunk.Equals(_lastViewerChunk)) // if nothing changed since the last frames the results will be the same so we can exit
            {
                return;
            }
            _lastViewerChunk = viewerChunk;
            _hasLastViewerChunk = true;
            HashSet<ChunkCoord> visibleChunks =
                _chunkStreamer.ComputeVisibleChunks(
                    viewerPosition,
                    _viewDistanceInChunks
                ); // get the visible chunks calculated by the streamer
            foreach (ChunkCoord coord in visibleChunks)
            {
                if (_chunkStates.TryGetValue(coord, out var state)) // try to get the current state of that chunk
                {
                    if (state != ChunkLifecycleState.Unloaded) // if the chunk is anything else than unloaded (like loaded, generating etc.) we dont need to do anything
                        continue;
                }
                _chunkStates[coord] = ChunkLifecycleState.Queued; // set the state to queued
                _loadQueue.Enqueue(coord); // append it to the load queue
            }
            HashSet<ChunkCoord> chunksToUnload = new(_chunks.Keys);
            chunksToUnload.ExceptWith(visibleChunks); // every chunk thats currently loaded but doesnt need to be loaded gets unloaded
            foreach (ChunkCoord coord in chunksToUnload)
            {
                if (!_chunkStates.TryGetValue(coord, out var state)) // if its state doesnt exist anymore it indicates that it probably got unloaded already
                    continue;
                if (state != ChunkLifecycleState.Loaded) // if its currently unloaded, building, queued, etc. we ignore it
                    continue;
                _chunkStates[coord] = ChunkLifecycleState.QueuedForUnload;
                _unloadQueue.Enqueue(coord);
            }
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStates, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStreamer, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._hasLastViewerChunk, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._lastViewerChunk, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._loadQueue, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._unloadQueue, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._viewDistanceInChunks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkSize, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.Update().
UnloadChunk()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.UnloadChunk (ChunkCoord coord) inline private
unloads the chunk at a given position
Parameters
coord the coordinate of the chunk to unload
Definition at line 266 of file GridChunkManager.cs.
        {
            _chunks[coord].DensityField.Dispose(); // dispose the density field of that chunk to free up memory
            _chunks.Remove(coord); // remove its data
            _chunkStates.Remove(coord); // and state
            ChunkChange?.Invoke(
                new ChunkChange(coord, ChunkChangeType.Unload) // and report the change to the listeners
            );
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStates, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkChange.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues().
Update()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.Update (float3 viewerPosition) inline
updates the chunk manager. this should be called once per frame. it processes the completed chunk generations, syncs the loaded chunks with the viewers position and processes the load / unload queues. this should only be called by the renderer as it is inefficient to update the manager multiple times per frame as it only changes across frames and not within a single frame.
Parameters
viewerPosition the position of the viewer as a world position
Definition at line 100 of file GridChunkManager.cs.
        {
            ProcessCompletedChunks();
            SyncChunks(viewerPosition);
            ProcessQueues();
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.Update().
Member Data Documentation
_activeGenerationTasks
int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._activeGenerationTasks private
Definition at line 42 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues().
_chunkGenerator
readonly ChunkGenerator _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkGenerator private
Definition at line 32 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GridChunkManager().
_chunks
readonly Dictionary<ChunkCoord, ChunkData> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunks = new() private
Definition at line 18 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetChunkAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GetLoadedChunkCoords(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.UnloadChunk().
_chunkStates
readonly Dictionary<ChunkCoord, ChunkLifecycleState> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStates = new() private
Definition at line 19 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.UnloadChunk().
_chunkStreamer
readonly ChunkStreamer _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._chunkStreamer private
Definition at line 35 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GridChunkManager(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
_completedChunks
readonly ConcurrentQueue<(ChunkCoord coord, ChunkData data)> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._completedChunks private
Initial value:
=
                new()
Definition at line 28 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GenerateChunkAsync(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks().
_hasLastViewerChunk
bool _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._hasLastViewerChunk private
Definition at line 40 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
_lastViewerChunk
int3 _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._lastViewerChunk private
Definition at line 38 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
_loadQueue
readonly Queue<ChunkCoord> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._loadQueue private
Initial value:
=
                new()
Definition at line 22 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
_unloadQueue
readonly Queue<ChunkCoord> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._unloadQueue = new() private
Definition at line 25 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
_viewDistanceInChunks
readonly int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager._viewDistanceInChunks private
Definition at line 50 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GridChunkManager(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
ChunkSize
readonly int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkSize
Definition at line 47 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.GridChunkManager(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
ChunksPerFrame
const int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunksPerFrame = 20 static private
Definition at line 44 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues().
MaxConcurrentGenerationTasks
const int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.MaxConcurrentGenerationTasks = 8 static private
Definition at line 45 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessQueues().
Event Documentation
ChunkChange
Action<ChunkChange> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ChunkChange
Definition at line 53 of file GridChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.ProcessCompletedChunks(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.UnloadChunk().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/GridChunkSystem/GridChunkManager.cs