Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Deprecated.Planet Class Reference
_Project.World.Planet.Scripts.Deprecated.Planet Class Reference
Public Attributes
int resolution = 10
Private Member Functions
void OnValidate ()
void Update ()
void Initialize ()
void GenerateMesh ()
Private Attributes
bool _needsGeneration
MeshFilter[] meshFilters
TerrainFace[] _terrainFaces
Detailed Description
Definition at line 7 of file PlanetOctahedron.cs.
Member Function Documentation
GenerateMesh()
void _Project.World.Planet.Scripts.Deprecated.Planet.GenerateMesh () inline private
Definition at line 107 of file PlanetOctahedron.cs.
        {
            foreach (TerrainFace face in _terrainFaces)
            {
                face.ConstructMesh();
            }
        }
References _Project.World.Planet.Scripts.Deprecated.Planet._terrainFaces, and _Project.World.Planet.Scripts.Deprecated.TerrainFace.ConstructMesh().
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.Update().
Initialize()
void _Project.World.Planet.Scripts.Deprecated.Planet.Initialize () inline private
Definition at line 45 of file PlanetOctahedron.cs.
        {
            // Ensure we have 8 mesh filters
            // (one for each octahedron face)
            if (meshFilters == null || meshFilters.Length != 8)
            {
                meshFilters = new MeshFilter[8];
            }
            _terrainFaces = new TerrainFace[8];
            // Vertices for an octahedron
            // Every 3 vertices define one triangle face
            Vector3[] vertices =
            {
                Vector3.up,Vector3.right,Vector3.forward,
                Vector3.up,Vector3.back,Vector3.right,
                Vector3.up,Vector3.left,Vector3.back,
                Vector3.up,Vector3.forward,Vector3.left,
                Vector3.forward,Vector3.right,Vector3.down,
                Vector3.right,Vector3.back,Vector3.down,
                Vector3.back,Vector3.left,Vector3.down,
                Vector3.left,Vector3.forward,Vector3.down
            };
            // Create all 8 triangle faces
            for (int i = 0; i < 8; i++)
            {   //name the faces for unity to know which face is generated and referenced
                string faceName = $"OctaFace_{i}";
                // reconnect to reference
                if (meshFilters[i] == null)
                {
                    Transform child = transform.Find(faceName);
                    if (child != null)
                    {
                        meshFilters[i] = child.GetComponent<MeshFilter>();
                    }
                }
                //if they still does not exist meaning there is no reference
                if (meshFilters[i] == null)
                {
                    GameObject meshObj = new GameObject(faceName)
                    {
                        transform =
{
                            // Parent meshes to the planet object
                            parent = transform
                        }
                    };
                    // Add renderer + material
                    meshObj.AddComponent<MeshRenderer>().sharedMaterial = new Material(Shader.Find("Standard"));
                    // Add mesh filter with empty mesh
                    meshFilters[i] = meshObj.AddComponent<MeshFilter>();
                    meshFilters[i].sharedMesh = new Mesh();
                }
                // Get the 3 vertices for this triangle face skipped triCount for i variable
                Vector3[] vert = {vertices[i*3],vertices[i*3+1],vertices[i*3+2]};
                // Create terrain face for this triangle
                _terrainFaces[i] = new TerrainFace(meshFilters[i].sharedMesh, resolution, vert);
            }
        }
References _Project.World.Planet.Scripts.Deprecated.Planet._terrainFaces, _Project.World.Planet.Scripts.Deprecated.Planet.meshFilters, and _Project.World.Planet.Scripts.Deprecated.Planet.resolution.
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.Update().
OnValidate()
void _Project.World.Planet.Scripts.Deprecated.Planet.OnValidate () inline private
Definition at line 23 of file PlanetOctahedron.cs.
        {
            //Just set the flag, do NO structural work here
            if (gameObject.activeInHierarchy)
            {
                _needsGeneration = true;
            }
        }
References _Project.World.Planet.Scripts.Deprecated.Planet._needsGeneration.
Update()
void _Project.World.Planet.Scripts.Deprecated.Planet.Update () inline private
Definition at line 32 of file PlanetOctahedron.cs.
        {
            //update is safe for structural change to meshes etc
            if (_needsGeneration)
            {
                Initialize();
                GenerateMesh();
                // Reset the flag so it only runs once per change
                _needsGeneration = false;
            }
        }
References _Project.World.Planet.Scripts.Deprecated.Planet._needsGeneration, _Project.World.Planet.Scripts.Deprecated.Planet.GenerateMesh(), and _Project.World.Planet.Scripts.Deprecated.Planet.Initialize().
Member Data Documentation
_needsGeneration
bool _Project.World.Planet.Scripts.Deprecated.Planet._needsGeneration private
Definition at line 10 of file PlanetOctahedron.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.OnValidate(), and _Project.World.Planet.Scripts.Deprecated.Planet.Update().
_terrainFaces
TerrainFace [] _Project.World.Planet.Scripts.Deprecated.Planet._terrainFaces private
Definition at line 18 of file PlanetOctahedron.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.GenerateMesh(), and _Project.World.Planet.Scripts.Deprecated.Planet.Initialize().
meshFilters
MeshFilter [] _Project.World.Planet.Scripts.Deprecated.Planet.meshFilters private
Definition at line 16 of file PlanetOctahedron.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.Initialize().
resolution
int _Project.World.Planet.Scripts.Deprecated.Planet.resolution = 10
Definition at line 13 of file PlanetOctahedron.cs.
Referenced by _Project.World.Planet.Scripts.Deprecated.Planet.Initialize().
The documentation for this class was generated from the following file:
Assets/_Project/World/Planet/Scripts/Deprecated/PlanetOctahedron.cs