Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer Class Reference
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer Class Reference
A chunk is a region of density values in space. it is used to split the terrain into multiple portions and put these chunks next to each other to allow dynamic loading / unloading of specific regions, different LODs (Levels of Details) and more.
Public Member Functions
void ApplyMeshData (Mesh mesh)
applies a given mesh to this renderer
Private Member Functions
void Awake ()
void EnsureComponents ()
void SetupMaterial ()
Private Attributes
MeshFilter _meshFilter
MeshRenderer _meshRenderer
Detailed Description
A chunk is a region of density values in space. it is used to split the terrain into multiple portions and put these chunks next to each other to allow dynamic loading / unloading of specific regions, different LODs (Levels of Details) and more.
Definition at line 10 of file ChunkRenderer.cs.
Member Function Documentation
ApplyMeshData()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.ApplyMeshData (Mesh mesh) inline
applies a given mesh to this renderer
Parameters
mesh
Definition at line 47 of file ChunkRenderer.cs.
        {
            EnsureComponents(); // ensure the renderer and filter are available
            SetupMaterial(); // and also ensure a material is set for the renderer so that the mesh is actually visible
            _meshFilter.mesh = mesh; // finally apply the mesh to the filter for it to get rendered
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.EnsureComponents(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.SetupMaterial().
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.CreateRendererAt(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkSystemRenderer.UpdateRendererAt().
Awake()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.Awake () inline private
Definition at line 15 of file ChunkRenderer.cs.
        {
            EnsureComponents();
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.EnsureComponents().
EnsureComponents()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.EnsureComponents () inline private
Definition at line 21 of file ChunkRenderer.cs.
        {
            if (_meshFilter == null)
                _meshFilter = gameObject.GetComponent<MeshFilter>() ?? gameObject.AddComponent<MeshFilter>();
            if (_meshRenderer == null)
                _meshRenderer = gameObject.GetComponent<MeshRenderer>() ?? gameObject.AddComponent<MeshRenderer>();
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer._meshFilter, and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer._meshRenderer.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.ApplyMeshData(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.Awake().
SetupMaterial()
void _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.SetupMaterial () inline private
Definition at line 29 of file ChunkRenderer.cs.
        {
            if (_meshRenderer.sharedMaterial != null) return; // if a material is already set we dont need to set one ourselves
            Shader shader = Shader.Find("Universal Render Pipeline/Lit") // use the default lit shader
                            ?? Shader.Find("Standard"); // or the standard one as a backup
            var mat = new Material(shader); // apply that shader to a new material
            _meshRenderer.sharedMaterial = mat; // and apply that material to the renderer
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer._meshRenderer.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.ApplyMeshData().
Member Data Documentation
_meshFilter
MeshFilter _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer._meshFilter private
Definition at line 12 of file ChunkRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.EnsureComponents().
_meshRenderer
MeshRenderer _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer._meshRenderer private
Definition at line 13 of file ChunkRenderer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.EnsureComponents(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkRenderer.SetupMaterial().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/GridChunkSystem/ChunkRenderer.cs