Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager Class Reference
_Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager Class Reference
Public Member Functions
OctreeChunkManager (Vector3Int origin, float size, BurstSamplerSettings densitySamplerSettings)
void RebuildOctree ()
OctreeChunkData GetChunkAt (NodeKey coord)
returns the chunk data of a given position. if no chunk exists at that position, null is returned.
IEnumerable< NodeKey > GetLoadedChunkCoords ()
returns the coordinates of the currently loaded chunks
void Update (float3 viewerPosition)
updates the chunk manager. this should be called once per frame. it processes the completed chunk generations, syncs the loaded chunks with the viewers position and processes the load / unload queues. this should only be called by the renderer as it is inefficient to update the manager multiple times per frame as it only changes across frames and not within a single frame.
Public Attributes
Octree Octree
int3 Origin
float Size
Events
Action< NodeChange > NodeChange
Private Member Functions
void ProcessQueues ()
loads / unloads chunks if they are in the different queueues. it doesnt check what chunks need to be loaded / unloaded!
void SyncChunks (float3 viewerPosition)
syncs the loaded chunks with the viewers position. it calculates what chunks should be loaded based on the viewers position and the view distance and adds those to the load queue if they are not already loaded. it also calculates what chunks should be unloaded and adds those to the unload queue if they are currently loaded. it does not actually loads or unloads the chunks, the processQueues method is responsible for that.
async Task GenerateChunkAsync (NodeKey coord)
generates a chunk at a given position using the chunk generator
void ProcessCompletedChunks ()
processes the completed chunk generations. it shifts the generated data from the _completedChunks queue to the main _chunks and _chunkStates dictionaries and triggers the chunk change event for the loaded chunks. this should only be called in the main thread (like in the update method) as it accesses the main dictionaries that are not thread safe.
void UnloadChunk (NodeKey coord)
unloads the chunk at a given position
Private Attributes
readonly Dictionary< NodeKey, OctreeChunkData > _chunks = new()
readonly Dictionary< NodeKey, OctreeChunkLifecycleState > _chunkStates = new()
BurstSamplerSettings _densitySamplerSettings
readonly Queue< NodeKey > _loadQueue
readonly Queue< NodeKey > _unloadQueue = new()
readonly ConcurrentQueue<(NodeKey coord, OctreeChunkData data)> _completedChunks
readonly ChunkGenerator _chunkGenerator
int3 _lastViewerChunk
bool _hasLastViewerChunk
int _activeGenerationTasks
readonly int _viewDistanceInChunks
Static Private Attributes
const int ChunksPerFrame = 20
const int MaxConcurrentGenerationTasks = 2
Detailed Description
Definition at line 14 of file OctreeChunkManager.cs.
Constructor & Destructor Documentation
OctreeChunkManager()
_Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.OctreeChunkManager (Vector3Int origin, float size, BurstSamplerSettings densitySamplerSettings) inline
Parameters
origin the origin world pos of the system
size the size of the system in world space
densitySamplerSettings the settings used for generating the density values
Definition at line 59 of file OctreeChunkManager.cs.
        {
            Origin = new int3(origin.x, origin.y, origin.z);
            Size = size;
            /*_chunkGenerator = new ChunkGenerator(
                densitySamplerSettings,
                chunkSize
            );*/
            _densitySamplerSettings = densitySamplerSettings;
            RebuildOctree();
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._densitySamplerSettings, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Origin, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Size.
Member Function Documentation
GenerateChunkAsync()
async Task _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GenerateChunkAsync (NodeKey coord) inline private
generates a chunk at a given position using the chunk generator
Parameters
coord the coordinate of the chunk that gets generated
Definition at line 214 of file OctreeChunkManager.cs.
        {
            Interlocked.Increment(ref _activeGenerationTasks); // keep track of the current amount of chunks that are being generated since they can generate across multiple frames
            _chunkStates[coord] = OctreeChunkLifecycleState.Generating; // set the current state to generating
            try
            {
                //OctreeChunkData chunkData = await Task.Run(() => ); // run the generation job
                //TODO
                //_completedChunks.Enqueue((coord, chunkData)); // and add its data afterward.
                                                              // this _completedChunks queue will get processed in the main thread in the update method to shift the
                                                              // generated data over to the main dictionaries and trigger the chunk change event
            }
            catch (Exception e)
            {
                // ReSharper disable once Unity.PerformanceCriticalCodeInvocation
                Debug.LogException(e);
            }
            finally
            {
                Interlocked.Decrement(ref _activeGenerationTasks); // and finally (even if the task failed) remove it from the active tasks count
            }
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._activeGenerationTasks, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunkStates.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
GetChunkAt()
OctreeChunkData _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GetChunkAt (NodeKey coord) inline
returns the chunk data of a given position. if no chunk exists at that position, null is returned.
Parameters
coord the coordinate of the chunk
Returns
the chunk data of the chunk at that position. may be null.
Definition at line 88 of file OctreeChunkManager.cs.
        {
            return _chunks.GetValueOrDefault(coord, null);
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunks.
GetLoadedChunkCoords()
IEnumerable< NodeKey > _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GetLoadedChunkCoords () inline
returns the coordinates of the currently loaded chunks
Returns
the chunk coordinates of the currently loaded chunks
Definition at line 97 of file OctreeChunkManager.cs.
        {
            return _chunks.Keys;
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunks.
ProcessCompletedChunks()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks () inline private
processes the completed chunk generations. it shifts the generated data from the _completedChunks queue to the main _chunks and _chunkStates dictionaries and triggers the chunk change event for the loaded chunks. this should only be called in the main thread (like in the update method) as it accesses the main dictionaries that are not thread safe.
Definition at line 244 of file OctreeChunkManager.cs.
        {
            while (_completedChunks.TryDequeue(out var result)) // every completed chunk gets processed
            {
                NodeKey coord = result.coord;
                OctreeChunkData data = result.data;
                if (!_chunkStates.TryGetValue(coord, out var state)) // if the state of the chunk doesnt exist, its broken as the state is already generated before starting the generation task. so to prevent further errors we just ignore that case
                    continue;
                if (state != OctreeChunkLifecycleState.Generating) // the state should currently be in the "generating" phase
                    continue;
                _chunks[coord] = data; // apply the data to the main chunks dictionary
                _chunkStates[coord] = OctreeChunkLifecycleState.Loaded; // and update the state to loaded
                NodeChange?.Invoke( // report the change to the listeners
                    new NodeChange(coord, Unity.NodeChange.NodeChangeType.Load)
                );
            }
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunks, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunkStates, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._completedChunks, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.NodeChange.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Update().
ProcessQueues()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues () inline private
loads / unloads chunks if they are in the different queueues. it doesnt check what chunks need to be loaded / unloaded!
Definition at line 120 of file OctreeChunkManager.cs.
        {
            int chunkCounter = 0; // counts the chunks we loaded or unloaded in this frame
            while
                (chunkCounter <
                 ChunksPerFrame) // we only want to load / unload a certain amount of chunks per frame to avoid performance spikes
            {
                if (_unloadQueue.Count <= 0) // break the loop if there are no more chunks to unload
                    break;
                NodeKey coord = _unloadQueue.Dequeue(); // retrieve a chunk coord to unload from the queue
                UnloadChunk(coord);
                chunkCounter++;
            }
            while
                (chunkCounter <
                 ChunksPerFrame) // we reuse the chunk counter without resetting it to ensure we only do a limited amount of operations (not loads and unloads) per frame
            {
                if (_activeGenerationTasks >=
                    MaxConcurrentGenerationTasks) // break if we cant start any more tasks this frame
                    break;
                if (_loadQueue.Count <= 0) // or break if the queue is empty
                    break;
                NodeKey coord = _loadQueue.Dequeue();
                _ = GenerateChunkAsync(
                    coord); // we dont need the result of the task as its already automatically getting stored, but we need to add a reference to the task for it to start so we just use a tmp variable
                chunkCounter++;
            }
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._activeGenerationTasks, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._loadQueue, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._unloadQueue, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ChunksPerFrame, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GenerateChunkAsync(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.MaxConcurrentGenerationTasks, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.UnloadChunk().
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Update().
RebuildOctree()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree () inline
Definition at line 78 of file OctreeChunkManager.cs.
        {
            Octree = OctreeHelper.Build(Origin, new int3((int) Size, (int) Size, (int) Size), _densitySamplerSettings, 6);
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._densitySamplerSettings, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Origin, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Size.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.OctreeChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemBootstrap.RebuildChunks().
SyncChunks()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.SyncChunks (float3 viewerPosition) inline private
syncs the loaded chunks with the viewers position. it calculates what chunks should be loaded based on the viewers position and the view distance and adds those to the load queue if they are not already loaded. it also calculates what chunks should be unloaded and adds those to the unload queue if they are currently loaded. it does not actually loads or unloads the chunks, the processQueues method is responsible for that.
Parameters
viewerPosition
Definition at line 164 of file OctreeChunkManager.cs.
        {
            //TODO
            /*
            int3 viewerChunk =
                (int3)math.floor(viewerPosition / ChunkSize); // convert world to chunk space
            if (_hasLastViewerChunk && viewerChunk.Equals(_lastViewerChunk)) // if nothing changed since the last frames the results will be the same so we can exit
            {
                return;
            }
            _lastViewerChunk = viewerChunk;
            _hasLastViewerChunk = true;
            foreach (NodeKey coord in visibleChunks)
            {
                if (_chunkStates.TryGetValue(coord, out var state)) // try to get the current state of that chunk
                {
                    if (state != OctreeChunkLifecycleState.Unloaded) // if the chunk is anything else than unloaded (like loaded, generating etc.) we dont need to do anything
                        continue;
                }
                _chunkStates[coord] = OctreeChunkLifecycleState.Queued; // set the state to queued
                _loadQueue.Enqueue(coord); // append it to the load queue
            }
            HashSet<NodeKey> chunksToUnload = new(_chunks.Keys);
            chunksToUnload.ExceptWith(visibleChunks); // every chunk thats currently loaded but doesnt need to be loaded gets unloaded
            foreach (NodeKey coord in chunksToUnload)
            {
                if (!_chunkStates.TryGetValue(coord, out var state)) // if its state doesnt exist anymore it indicates that it probably got unloaded already
                    continue;
                if (state != OctreeChunkLifecycleState.Loaded) // if its currently unloaded, building, queued, etc. we ignore it
                    continue;
                _chunkStates[coord] = OctreeChunkLifecycleState.QueuedForUnload;
                _unloadQueue.Enqueue(coord);
            } */
        }
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Update().
UnloadChunk()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.UnloadChunk (NodeKey coord) inline private
unloads the chunk at a given position
Parameters
coord the coordinate of the chunk to unload
Definition at line 271 of file OctreeChunkManager.cs.
        {
            //_chunks[coord].DensityField.Dispose(); // dispose the density field of that chunk to free up memory
            _chunks.Remove(coord); // remove its data
            _chunkStates.Remove(coord); // and state
            NodeChange?.Invoke(
                new NodeChange(coord, Unity.NodeChange.NodeChangeType.Unload) // and report the change to the listeners
            );
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunks, _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunkStates, and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.NodeChange.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
Update()
void _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Update (float3 viewerPosition) inline
updates the chunk manager. this should be called once per frame. it processes the completed chunk generations, syncs the loaded chunks with the viewers position and processes the load / unload queues. this should only be called by the renderer as it is inefficient to update the manager multiple times per frame as it only changes across frames and not within a single frame.
Parameters
viewerPosition the position of the viewer as a world position
Definition at line 108 of file OctreeChunkManager.cs.
        {
            ProcessCompletedChunks();
            SyncChunks(viewerPosition);
            ProcessQueues();
        }
References _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.SyncChunks().
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.Update().
Member Data Documentation
_activeGenerationTasks
int _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._activeGenerationTasks private
Definition at line 44 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GenerateChunkAsync(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
_chunkGenerator
readonly ChunkGenerator _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunkGenerator private
Definition at line 37 of file OctreeChunkManager.cs.
_chunks
readonly Dictionary<NodeKey, OctreeChunkData> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunks = new() private
Definition at line 16 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GetChunkAt(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GetLoadedChunkCoords(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.UnloadChunk().
_chunkStates
readonly Dictionary<NodeKey, OctreeChunkLifecycleState> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._chunkStates = new() private
Definition at line 17 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.GenerateChunkAsync(), _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.UnloadChunk().
_completedChunks
readonly ConcurrentQueue<(NodeKey coord, OctreeChunkData data)> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._completedChunks private
Initial value:
=
                new()
Definition at line 33 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks().
_densitySamplerSettings
BurstSamplerSettings _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._densitySamplerSettings private
Definition at line 24 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.OctreeChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree().
_hasLastViewerChunk
bool _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._hasLastViewerChunk private
Definition at line 42 of file OctreeChunkManager.cs.
_lastViewerChunk
int3 _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._lastViewerChunk private
Definition at line 40 of file OctreeChunkManager.cs.
_loadQueue
readonly Queue<NodeKey> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._loadQueue private
Initial value:
=
                new()
Definition at line 27 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
_unloadQueue
readonly Queue<NodeKey> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._unloadQueue = new() private
Definition at line 30 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
_viewDistanceInChunks
readonly int _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager._viewDistanceInChunks private
Definition at line 51 of file OctreeChunkManager.cs.
ChunksPerFrame
const int _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ChunksPerFrame = 20 static private
Definition at line 46 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
MaxConcurrentGenerationTasks
const int _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.MaxConcurrentGenerationTasks = 2 static private
Definition at line 47 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessQueues().
Octree
Octree _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Octree
Definition at line 19 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.Unity.OctreeChunkSystemRenderer.OnDrawGizmos().
Origin
int3 _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Origin
Definition at line 21 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.OctreeChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree().
Size
float _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.Size
Definition at line 22 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.OctreeChunkManager(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.RebuildOctree().
Event Documentation
NodeChange
Action<NodeChange> _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.NodeChange
Definition at line 54 of file OctreeChunkManager.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.ProcessCompletedChunks(), and _Project.World.Planet.Scripts.Chunking.OctreeChunkSystem.OctreeChunkManager.UnloadChunk().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/OctreeChunkSystem/OctreeChunkManager.cs