Openworld Factory (Name WIP): _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer Class Reference
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer Class Reference
the chunk streamer is responsible for calculating what chunks to display. it has no reference to any chunk systems and only contains a function that returns a set of chunks that should be visible based on the viewers position (in world pos). everything else is managed by the chunk manager.
Public Member Functions
ChunkStreamer (int chunkSize)
HashSet< ChunkCoord > ComputeVisibleChunks (float3 viewerPosition, int viewDistanceInChunks)
calculates the visible chunks based on the viewers position and the view distance in chunks
Private Attributes
readonly int _chunkSize
ChunkCoord _lastCalculatedChunkCoord
bool _hasLastCalculated
HashSet< ChunkCoord > _lastVisibleChunks = new()
Detailed Description
the chunk streamer is responsible for calculating what chunks to display. it has no reference to any chunk systems and only contains a function that returns a set of chunks that should be visible based on the viewers position (in world pos). everything else is managed by the chunk manager.
Definition at line 12 of file ChunkStreamer.cs.
Constructor & Destructor Documentation
ChunkStreamer()
_Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ChunkStreamer (int chunkSize) inline
Definition at line 16 of file ChunkStreamer.cs.
        {
            _chunkSize = chunkSize;
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._chunkSize.
Member Function Documentation
ComputeVisibleChunks()
HashSet< ChunkCoord > _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks (float3 viewerPosition, int viewDistanceInChunks) inline
calculates the visible chunks based on the viewers position and the view distance in chunks
Parameters
viewerPosition the world position of the viewer
viewDistanceInChunks the viewers view distance in chunks. it is used as a radius of a sphere around the viewer where every chunk thats inside that sphere is returned.
Returns
a set of chunk coords of visible chunks
Definition at line 31 of file ChunkStreamer.cs.
        {
            ChunkCoord viewerChunk = new(
                (int3) math.floor(viewerPosition / _chunkSize)
            );
            if (viewDistanceInChunks <= 0)
            {
                _lastCalculatedChunkCoord = viewerChunk;
                _hasLastCalculated = true;
                _lastVisibleChunks.Clear();
                return new HashSet<ChunkCoord>();
            }
            if (_hasLastCalculated && _lastCalculatedChunkCoord.Equals(viewerChunk))
            {
                return new HashSet<ChunkCoord>(_lastVisibleChunks);
            }
            // calculate a sphere of chunks that need to be generated
            HashSet<ChunkCoord> visibleChunks = new();
            for (int x = -viewDistanceInChunks; x <= viewDistanceInChunks; x++)
            {
                for (int y = -viewDistanceInChunks; y <= viewDistanceInChunks; y++)
                {
                    for (int z = -viewDistanceInChunks; z <= viewDistanceInChunks; z++)
                    {
                        ChunkCoord chunkCoord = viewerChunk + new int3(x, y, z);
                        if (math.distance(viewerChunk.Value, chunkCoord.Value) <= viewDistanceInChunks)
{
                            visibleChunks.Add(chunkCoord);
                        }
                    }
                }
            }
            _lastCalculatedChunkCoord = viewerChunk;
            _hasLastCalculated = true;
            _lastVisibleChunks = visibleChunks;
            return new HashSet<ChunkCoord>(_lastVisibleChunks);
        }
References _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._chunkSize, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._hasLastCalculated, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._lastCalculatedChunkCoord, _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._lastVisibleChunks, _Project.World.Planet.Scripts.Chunking.Core.ChunkCoord.Equals(), and _Project.World.Planet.Scripts.Chunking.Core.ChunkCoord.Value.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.GridChunkManager.SyncChunks().
Member Data Documentation
_chunkSize
readonly int _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._chunkSize private
Definition at line 14 of file ChunkStreamer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ChunkStreamer(), and _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks().
_hasLastCalculated
bool _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._hasLastCalculated private
Definition at line 22 of file ChunkStreamer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks().
_lastCalculatedChunkCoord
ChunkCoord _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._lastCalculatedChunkCoord private
Definition at line 21 of file ChunkStreamer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks().
_lastVisibleChunks
HashSet<ChunkCoord> _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer._lastVisibleChunks = new() private
Definition at line 23 of file ChunkStreamer.cs.
Referenced by _Project.World.Planet.Scripts.Chunking.GridChunkSystem.ChunkStreamer.ComputeVisibleChunks().
The documentation for this class was generated from the following file:
World/Planet/Scripts/Chunking/GridChunkSystem/ChunkStreamer.cs