Openworld Factory (Name WIP): _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob Struct Reference
_Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob Struct Reference
Public Member Functions
void Execute ()
Public Attributes
DensityFieldData DensityField
NativeList< float3 > Vertices
NativeList< float3 > Normals
NativeList< int > Indices
NativeHashMap< VertexKey, int > VertexMap
float IsoLevel
NativeArray< int > EdgeTable
NativeArray< int > TriTable
Private Member Functions
void GenerateAt (int3 pos, DensityFieldData grid)
void AddTriangle (float3 a, VertexKey ka, float3 b, VertexKey kb, float3 c, VertexKey kc)
this adds a triangle to the mesh and calculates its indices and normals. this way you can just call this method for every triangle you want to add and it will take care of the rest.
int GetOrAddVertex (VertexKey key, float3 v)
checks if the given vertex already exists in the vertices list and if so returns its index, otherwise it adds it to the list and returns the new index
void NormalizeNormals ()
this normalizes the normals. that means every normal has a length of exactly 1.
Static Private Member Functions
static int GetCubeIndexAt (int3 pos, DensityFieldData grid, float isoLevel)
static int Tri (NativeArray< int > triTable, int cubeIndex, int i)
static float3 VertexInterp (float isoLevel, int3 p1, int3 p2, float valP1, float valP2)
Detailed Description
Definition at line 10 of file BurstMeshGeneratorJob.cs.
Member Function Documentation
AddTriangle()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.AddTriangle (float3 a, VertexKey ka, float3 b, VertexKey kb, float3 c, VertexKey kc) inline private
this adds a triangle to the mesh and calculates its indices and normals. this way you can just call this method for every triangle you want to add and it will take care of the rest.
Definition at line 11 of file BurstMeshGeneratorJob.MeshBuilder.cs.
        {
            if (!math.all(math.isfinite(a)) ||
                !math.all(math.isfinite(b)) ||
                !math.all(math.isfinite(c)))
                return;
            int i0 = GetOrAddVertex(ka, a);
            int i1 = GetOrAddVertex(kb, b);
            int i2 = GetOrAddVertex(kc, c);
            Indices.Add(i0);
            Indices.Add(i1);
            Indices.Add(i2);
            float3 normal = math.normalize(math.cross(b - a, c - a));
            Normals[i0] += normal;
            Normals[i1] += normal;
            Normals[i2] += normal;
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetOrAddVertex(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Indices, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Normals.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
Execute()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Execute () inline
Definition at line 28 of file BurstMeshGeneratorJob.cs.
        {
            int size = DensityField.Size - 2;
            for (int x = 0; x < size; x++)
            {
                for (int y = 0; y < size; y++)
                {
                    for (int z = 0; z < size; z++)
                    {
                        GenerateAt((new int3(x, y, z)),
                            DensityField); // generate the mesh for every grid cell and use the mesh builder to add it all to one large mesh
                    }
                }
            }
            NormalizeNormals();
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.DensityField, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt(), and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.NormalizeNormals().
GenerateAt()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt (int3 pos, DensityFieldData grid) inline private
Definition at line 10 of file BurstMeshGeneratorJob.Generation.cs.
        {
            int cubeIndex = GetCubeIndexAt(pos, grid, IsoLevel); // calculates the cube index at that position.
                                                                // look at the description of that function if you want to know what it does
            if (cubeIndex is 255 or 0) return;  // if the isosurface doesnt cut through any edge, we can skip this cube and return an empty list of triangles
            int edgeFlags = EdgeTable[cubeIndex]; // converts the given corner configuration to a binary number
            // where every bit represents one edge. note that we convert an 8 bit
            // number (one bit for every corner) to a 12 bit number (one bit for every edge).
            // we take that value from a huge precomputed table that contains the edge configuration
            // for every possible corner configuration. So every bit is 1 if the isosurface cuts through that edge.
            // the resulting vertices can be 12 max since there are only 12 edges. we fill the rest of the values with -1.
            Vtx* vertices = stackalloc Vtx[12];
            // helper vars for the single corners of the cube
            int3 p0 = new int3(pos.x, pos.y, pos.z);
            int3 p1 = new int3(pos.x + 1, pos.y, pos.z);
            int3 p2 = new int3(pos.x + 1, pos.y + 1, pos.z);
            int3 p3 = new int3(pos.x, pos.y + 1, pos.z);
            int3 p4 = new int3(pos.x, pos.y, pos.z + 1);
            int3 p5 = new int3(pos.x + 1, pos.y, pos.z + 1);
            int3 p6 = new int3(pos.x + 1, pos.y + 1, pos.z + 1);
            int3 p7 = new int3(pos.x, pos.y + 1, pos.z + 1);
            // here we check if the given bit is 1. the binary operator & acts as an AND mask, so
            // 0b11011101 & 0b01010011 = 0b01010001. this way we can check every edge separately.
            // c# doesnt let you directly cast ints to bools (1=true, 0=false) so we just compare it to 0 to know if its true or not
            if ((edgeFlags & 1) != 0)
            {
                vertices[0].Pos =
                    VertexInterp(IsoLevel, p0,
                        p1, // so we know now that this edge is used but if we just pass the center between the start and end point of that edge it would be way to blocky. so we just interpolate between the 2 densities of the corresponding values. this way everything is distributed smoothly.
                        grid.DensityAt(p0), grid.DensityAt(p1));
                vertices[0].Key = new VertexKey(pos, 0); // also store the key (consisting of the position and edge index) so that we can deduplicate the vertices later
            }
            if ((edgeFlags & 2) != 0) //same goes for every other edge type
            {
                vertices[1].Pos =
                    VertexInterp(IsoLevel, p1, p2,
                        grid.DensityAt(p1), grid.DensityAt(p2));
                vertices[1].Key = new VertexKey(pos, 1);
            }
            if ((edgeFlags & 4) != 0)
            {
                vertices[2].Pos =
                    VertexInterp(IsoLevel, p2, p3,
                        grid.DensityAt(p2), grid.DensityAt(p3));
                vertices[2].Key = new VertexKey(pos, 2);
            }
            if ((edgeFlags & 8) != 0)
            {
                vertices[3].Pos =
                    VertexInterp(IsoLevel, p3, p0,
                        grid.DensityAt(p3), grid.DensityAt(p0));
                vertices[3].Key = new VertexKey(pos, 3);
            }
            if ((edgeFlags & 16) != 0)
            {
                vertices[4].Pos =
                    VertexInterp(IsoLevel, p4, p5,
                        grid.DensityAt(p4), grid.DensityAt(p5));
                vertices[4].Key = new VertexKey(pos, 4);
            }
            if ((edgeFlags & 32) != 0)
            {
                vertices[5].Pos =
                    VertexInterp(IsoLevel, p5, p6,
                        grid.DensityAt(p5), grid.DensityAt(p6));
                vertices[5].Key = new VertexKey(pos, 5);
            }
            if ((edgeFlags & 64) != 0)
            {
                vertices[6].Pos =
                    VertexInterp(IsoLevel, p6, p7,
                        grid.DensityAt(p6), grid.DensityAt(p7));
                vertices[6].Key = new VertexKey(pos, 6);
            }
            if ((edgeFlags & 128) != 0)
            {
                vertices[7].Pos =
                    VertexInterp(IsoLevel, p7, p4,
                        grid.DensityAt(p7), grid.DensityAt(p4));
                vertices[7].Key = new VertexKey(pos, 7);
            }
            if ((edgeFlags & 256) != 0)
            {
                vertices[8].Pos =
                    VertexInterp(IsoLevel, p0, p4,
                        grid.DensityAt(p0), grid.DensityAt(p4));
                vertices[8].Key = new VertexKey(pos, 8);
            }
            if ((edgeFlags & 512) != 0)
            {
                vertices[9].Pos =
                    VertexInterp(IsoLevel, p1, p5,
                        grid.DensityAt(p1), grid.DensityAt(p5));
                vertices[9].Key = new VertexKey(pos, 9);
            }
            if ((edgeFlags & 1024) != 0)
            {
                vertices[10].Pos =
                    VertexInterp(IsoLevel, p2, p6,
                        grid.DensityAt(p2), grid.DensityAt(p6));
                vertices[10].Key = new VertexKey(pos, 10);
            }
            if ((edgeFlags & 2048) != 0)
            {
                vertices[11].Pos =
                    VertexInterp(IsoLevel, p3, p7,
                        grid.DensityAt(p3), grid.DensityAt(p7));
                vertices[11].Key = new VertexKey(pos, 11);
            }
            //now we need to convert the vertices to triangles and take just the filled ones
            //so we have the used edges but we dont know how the triangles are supposed to be generated to occupy the given edge configuration.
            // thats why we have another huge precomputed table that contains the triangle configuration for every possible edge configuration. so we just need to loop through that table until we find a -1 which marks the end of the triangle list for that edge configuration.
            for (int i = 0;
                 Tri(TriTable, cubeIndex, i) != -1;
                 i += 3) // go in steps of 3 (a triangle consists of 3 points) until we find a -1 which marks the end of that triangle list
            {
                int a = Tri(TriTable, cubeIndex, i);
                int b = Tri(TriTable, cubeIndex, i + 1);
                int c = Tri(TriTable, cubeIndex, i + 2);
                AddTriangle(
                    vertices[a].Pos, vertices[a].Key,
                    vertices[b].Pos, vertices[b].Key,
                    vertices[c].Pos, vertices[c].Key
                );
            }
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.AddTriangle(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.EdgeTable, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetCubeIndexAt(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.IsoLevel, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Tri(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.TriTable, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.VertexInterp().
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Execute().
GetCubeIndexAt()
static int _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetCubeIndexAt (int3 pos, DensityFieldData grid, float isoLevel) inline static private
Definition at line 171 of file BurstMeshGeneratorJob.Generation.cs.
        {
            int cubeIndex = 0;
            if (grid.DensityAt(pos.x, pos.y, pos.z) > isoLevel)
                cubeIndex |=
                    1; // the |= operator sets every bit that is set in the right operand to 1 in the left operand also to 1.
            // so if the left number (cubeIndex) is 0b11001000 and the right one (the mask, lets say 4) is 0b00000100 the result of that operation would be 0b11001100
            if (grid.DensityAt(pos.x + 1, pos.y, pos.z) > isoLevel) cubeIndex |= 2;
            if (grid.DensityAt(pos.x + 1, pos.y + 1, pos.z) > isoLevel) cubeIndex |= 4;
            if (grid.DensityAt(pos.x, pos.y + 1, pos.z) > isoLevel) cubeIndex |= 8;
            if (grid.DensityAt(pos.x, pos.y, pos.z + 1) > isoLevel) cubeIndex |= 16;
            if (grid.DensityAt(pos.x + 1, pos.y, pos.z + 1) > isoLevel) cubeIndex |= 32;
            if (grid.DensityAt(pos.x + 1, pos.y + 1, pos.z + 1) > isoLevel) cubeIndex |= 64;
            if (grid.DensityAt(pos.x, pos.y + 1, pos.z + 1) > isoLevel) cubeIndex |= 128;
            return cubeIndex;
        }
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
GetOrAddVertex()
int _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetOrAddVertex (VertexKey key, float3 v) inline private
checks if the given vertex already exists in the vertices list and if so returns its index, otherwise it adds it to the list and returns the new index
Definition at line 40 of file BurstMeshGeneratorJob.MeshBuilder.cs.
        {
            if (VertexMap.TryGetValue(key, out int index))
                return index;
            index = Vertices.Length;
            Vertices.Add(v);
            Normals.Add(float3.zero);
            VertexMap.Add(key, index);
            return index;
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Normals, _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.VertexMap, and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Vertices.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.AddTriangle().
NormalizeNormals()
void _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.NormalizeNormals () inline private
this normalizes the normals. that means every normal has a length of exactly 1.
Definition at line 58 of file BurstMeshGeneratorJob.MeshBuilder.cs.
        {
            for (int i = 0; i < Normals.Length; i++)
            {
                float3 n = Normals[i];
                if (!math.all(math.isfinite(n)) || math.lengthsq(n) < 1e-12f)
                {
                    Normals[i] = new float3(0f, 1f, 0f);
                    continue;
                }
                Normals[i] = math.normalize(n);
            }
        }
References _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Normals.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Execute().
Tri()
static int _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Tri (NativeArray< int > triTable, int cubeIndex, int i) inline static private
Definition at line 191 of file BurstMeshGeneratorJob.Generation.cs.
        {
            return triTable[cubeIndex * 16 + i];
        }
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
VertexInterp()
static float3 _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.VertexInterp (float isoLevel, int3 p1, int3 p2, float valP1, float valP2) inline static private
Definition at line 200 of file BurstMeshGeneratorJob.Generation.cs.
        {
            float3 p;
            if (math.abs(isoLevel - valP1) < 0.00001)
                return new float3(p1.x, p1.y, p1.z);
            if (math.abs(isoLevel - valP2) < 0.00001)
                return new float3(p2.x, p2.y, p2.z);
            if (math.abs(valP1 - valP2) < 0.00001)
                return new float3(p1.x, p1.y, p1.z);
            float mu = (isoLevel - valP1) / (valP2 - valP1);
            p.x = p1.x + mu * (p2.x - p1.x);
            p.y = p1.y + mu * (p2.y - p1.y);
            p.z = p1.z + mu * (p2.z - p1.z);
            return p;
        }
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
Member Data Documentation
DensityField
DensityFieldData _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.DensityField
Definition at line 12 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Execute().
EdgeTable
NativeArray<int> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.EdgeTable
Definition at line 25 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
Indices
NativeList<int> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Indices
Definition at line 16 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.AddTriangle().
IsoLevel
float _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.IsoLevel
Definition at line 23 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
Normals
NativeList<float3> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Normals
Definition at line 15 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.AddTriangle(), _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetOrAddVertex(), and _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.NormalizeNormals().
TriTable
NativeArray<int> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.TriTable
Definition at line 26 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GenerateAt().
VertexMap
NativeHashMap<VertexKey, int> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.VertexMap
Definition at line 19 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetOrAddVertex().
Vertices
NativeList<float3> _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.Vertices
Definition at line 14 of file BurstMeshGeneratorJob.cs.
Referenced by _Project.World.Planet.Scripts.MarchingCubes.MeshGeneration.Core.BurstMeshGeneratorJob.GetOrAddVertex().
The documentation for this struct was generated from the following files:
World/Planet/Scripts/MarchingCubes/MeshGeneration/Core/BurstMeshGeneratorJob.cs
World/Planet/Scripts/MarchingCubes/MeshGeneration/Core/BurstMeshGeneratorJob.Generation.cs
World/Planet/Scripts/MarchingCubes/MeshGeneration/Core/BurstMeshGeneratorJob.MeshBuilder.cs